inc/buzzer.h File Reference
Header file for buzzer.c.
#include `inc/main.h`
Macros
#define BUZZER_PORT (GPIO_PORTG_BASE)
#define BUZZER_PIN (GPIO_PIN_0)
#define MAX_FREQ (2048)
#define FREQ_1 ()
Functions
void buzzer_config (void)
This function configures the GPIOs required for the buzzer.
void buzzer_dutycycle (uint32_t freq)
This function sets the duty cycle of the buzzer.
void buzzer_onoff (bool state)
This function switches the buzzer on/off.
void buzzer_test (void)
This function is used for testing.
Detailed Description
Header file for buzzer.c.
The file consists of all the function declarations, macros and typedefs related to Buzzer. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/19/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
BUZZER_PIN
#define BUZZER_PIN (GPIO_PIN_0)
GPIO pin for buzzer
Definition at line 26 of file buzzer.h.
Referenced by buzzer_config().
BUZZER_PORT
#define BUZZER_PORT (GPIO_PORTG_BASE)
GPIO port for buzzer
Definition at line 25 of file buzzer.h.
Referenced by buzzer_config().
FREQ_1
#define FREQ_1 ()
Definition at line 34 of file buzzer.h.
MAX_FREQ
#define MAX_FREQ (2048)
This is the maximum frequency value for the buffer
Definition at line 33 of file buzzer.h.
Referenced by buzzer_test().
Function Documentation
buzzer_config()
void buzzer_config (void)
This function configures the GPIOs required for the buzzer.
Returns
void.
Definition at line 17 of file buzzer.c.
References BUZZER_PIN, and BUZZER_PORT.
Referenced by buzzer_test().
buzzer_dutycycle()
void buzzer_dutycycle (uint32_t freq)
This function sets the duty cycle of the buzzer.
Parameters
freq The frequency value provided for the buzzer to vary sound.
Returns
void.
Definition at line 45 of file buzzer.c.
References g_ui32SysClock.
Referenced by buzzer_test().
buzzer_onoff()
void buzzer_onoff (bool state)
This function switches the buzzer on/off.
Parameters
state The state parameter represents on or off. Non-zero value represents ON, Zero represents OFF.
Returns
void.
Definition at line 59 of file buzzer.c.
Referenced by uart_packet_handler().
buzzer_test()
void buzzer_test (void)
This function is used for testing.
Returns
void.
Definition at line 74 of file buzzer.c.
References buzzer_config(), buzzer_dutycycle(), and MAX_FREQ.