src/buzzer.c File Reference
This file consists of all the functions required for the Buzzer.
#include `inc/buzzer.h`
#include `driverlib/pwm.h`
Functions
void buzzer_config (void)
This function configures the GPIOs required for the buzzer.
void buzzer_dutycycle (uint32_t freq)
This function sets the duty cycle of the buzzer.
void buzzer_onoff (bool state)
This function switches the buzzer on/off.
void buzzer_test (void)
This function is used for testing.
Detailed Description
This file consists of all the functions required for the Buzzer.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/19/2019
Copyright
Copyright (c) 2019
Function Documentation
buzzer_config()
void buzzer_config (void)
This function configures the GPIOs required for the buzzer.
Returns
void.
Definition at line 17 of file buzzer.c.
References BUZZER_PIN, and BUZZER_PORT.
Referenced by buzzer_test().
buzzer_dutycycle()
void buzzer_dutycycle (uint32_t freq)
This function sets the duty cycle of the buzzer.
Parameters
freq The frequency value provided for the buzzer to vary sound.
Returns
void.
Definition at line 45 of file buzzer.c.
References g_ui32SysClock.
Referenced by buzzer_test().
buzzer_onoff()
void buzzer_onoff (bool state)
This function switches the buzzer on/off.
Parameters
state The state parameter represents on or off. Non-zero value represents ON, Zero represents OFF.
Returns
void.
Definition at line 59 of file buzzer.c.
Referenced by uart_packet_handler().
buzzer_test()
void buzzer_test (void)
This function is used for testing.
Returns
void.
Definition at line 74 of file buzzer.c.
References buzzer_config(), buzzer_dutycycle(), and MAX_FREQ.