src/checksum.c File Reference
This file consists of all the functions required for Checksum.
#include `inc/checksum.h`
Functions
void checksum_init (void)
This function initializes the Checksum functionality and stores all the possible combinations in a table.
crc checksum_calc (uint8_t const message[], int nBytes)
This function calculates the Checksum for the specified data.
Detailed Description
This file consists of all the functions required for Checksum.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/20/2019
See also
https://barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code
Copyright
Copyright (c) 2019
Function Documentation
checksum_calc()
crc checksum_calc (uint8_t const message[], int nBytes)
This function calculates the Checksum for the specified data.
Parameters
message The array containing the Message Data.
nBytes The Number of bytes in the Array.
Returns
crc.
Definition at line 63 of file checksum.c.
References crcTable, and WIDTH.
Referenced by packet_make(), packet_rcv_uart(), and uart_packet_handler().
checksum_init()
void checksum_init (void)
This function initializes the Checksum functionality and stores all the possible combinations in a table.
Returns
void.
Definition at line 20 of file checksum.c.
References crcTable, POLYNOMIAL, TOPBIT, and WIDTH.