inc/checksum.h File Reference
Header file for checksum.c.
#include `inc/main.h`
Macros
#define WIDTH (8 * sizeof(crc))
#define TOPBIT (1 << (WIDTH - 1))
#define POLYNOMIAL (0xD8)
Typedefs
typedef uint16_t crc
Functions
void checksum_init (void)
This function initializes the Checksum functionality and stores all the possible combinations in a table.
crc checksum_calc (uint8_t const message[], int nBytes)
This function calculates the Checksum for the specified data.
Variables
crc crcTable [256]
Detailed Description
Header file for checksum.c.
The file consists of all the function declarations, macros and typedefs related to Checksum. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/20/2019
See also
https://barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code
Copyright
Copyright (c) 2019
Macro Definition Documentation
POLYNOMIAL
#define POLYNOMIAL (0xD8)
Definition at line 27 of file checksum.h.
Referenced by checksum_init().
TOPBIT
#define TOPBIT (1 << (WIDTH - 1))
Definition at line 26 of file checksum.h.
Referenced by checksum_init().
WIDTH
#define WIDTH (8 * sizeof(crc))
Definition at line 25 of file checksum.h.
Referenced by checksum_calc(), and checksum_init().
Typedef Documentation
crc
typedef uint16_t crc
Definition at line 22 of file checksum.h.
Function Documentation
checksum_calc()
crc checksum_calc (uint8_t const message[], int nBytes)
This function calculates the Checksum for the specified data.
Parameters
message The array containing the Message Data.
nBytes The Number of bytes in the Array.
Returns
crc.
Definition at line 63 of file checksum.c.
References crcTable, and WIDTH.
Referenced by packet_make(), packet_rcv_uart(), and uart_packet_handler().
checksum_init()
void checksum_init (void)
This function initializes the Checksum functionality and stores all the possible combinations in a table.
Returns
void.
Definition at line 20 of file checksum.c.
References crcTable, POLYNOMIAL, TOPBIT, and WIDTH.
Variable Documentation
crcTable
crc crcTable[256]
Definition at line 23 of file checksum.h.
Referenced by checksum_calc(), and checksum_init().