src/fingerprint.c File Reference
This file consists of all the functions required for the Fingerprint Scanner GT-521F32.
#include `inc/fingerprint.h`
#include `inc/packet.h`
#include `inc/lcd.h`
#include `inc/timer.h`
Functions
void fp_interrupt_config (void)
This function initializes and enables the required GPIO pins interrupts for fingerprint sensor GT-521F32.
void fp_cmdsend (uart_t uart, uint8_t cmd, uint8_t param)
This function sends the command to the Fingerprint Sensor GT-521F32 via UART.
uint16_t fp_responsercv (uart_t uart)
This function receives the response packet from the Fingerprint Sensor GT-521F32 and returns the output parameter/error code.
uint16_t fp_checksum_calc (uint8_t packet[])
This function calculates the checksum as specfied in the datasheet of Fingerprint GT-521F32.
uint16_t fp_start_enroll (uart_t uart, uint16_t new_id)
This function Starts the fingerprint Enrollment process.
void fp_enroll (uart_t uart, uint8_t enroll_cmd)
This function enrolls the fingerprint.
void add_fingerprint (uart_t uart)
This function adds a fingerprint.
uint16_t fp_baudrate (uart_t uart, uint16_t baudrate)
This function changes the baudrate. The default baudrate is 9600.
uint16_t fp_deleteid (uart_t uart, uint16_t id)
This function deletes the specified Fingerprint ID.
uint16_t fp_verify (uart_t uart, uint16_t id)
This function verifies the latest captured fingerprint.
uint16_t fp_identify (uart_t uart)
This function identifies the captured fingerprint from the stored fingerprints and returns the ID.
void fp_access_handle (void)
void fp_irqhandler (void)
Callback function for Fingerprint Interrupt Handler.
void fingerprint_test (void)
This function was used for testing purposes.
Detailed Description
This file consists of all the functions required for the Fingerprint Scanner GT-521F32.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/19/2019
Copyright
Copyright (c) 2019
Function Documentation
add_fingerprint()
void add_fingerprint (uart_t uart)
This function adds a fingerprint.
Parameters
uart The UART line used.
Returns
void.
Definition at line 177 of file fingerprint.c.
References fp_enroll(), FP_ENROLL1_CMD, FP_ENROLL2_CMD, FP_ENROLL3_CMD, fp_get_enrollcount(), FP_IRQ_PIN, FP_IRQ_PORT, fp_start_enroll(), and printf.
Referenced by uart_packet_handler().
fingerprint_test()
void fingerprint_test (void)
This function was used for testing purposes.
Returns
void.
Definition at line 400 of file fingerprint.c.
References fp_led_status(), FP_LEDON, fp_open(), and UART_FP.
fp_access_handle()
void fp_access_handle (void)
Definition at line 332 of file fingerprint.c.
References DONT_CARE, FINGERPRINT_ID, FINGERPRINT_MATCHED, FINGERPRINT_NOTMATCHED, fp_capture(), fp_identify(), FP_LOW_IMAGE, FP_NACK_DB_IS_EMPTY, FP_NACK_IDENTIFY_FAILED, LCD_write(), packet_make(), packet_send_uart(), printf, TRUE, UART_BBG, and UART_FP.
Referenced by fp_irqhandler().
fp_baudrate()
uint16_t fp_baudrate (uart_t uart, uint16_t baudrate)
This function changes the baudrate. The default baudrate is 9600.
Parameters
uart The UART line used.
baudrate The baudrate MACRO:
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 225 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, FP_BAUDRATE_CMD, fp_checksum_calc(), fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
fp_checksum_calc()
uint16_t fp_checksum_calc (uint8_t packet[])
This function calculates the checksum as specfied in the datasheet of Fingerprint GT-521F32.
Parameters
packet The Response/Command packet array as per the datasheet of GT-521F32.
Returns
uint16_t The calculated checksum value.
Definition at line 108 of file fingerprint.c.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
fp_cmdsend()
void fp_cmdsend (uart_t uart, uint8_t cmd, uint8_t param)
This function sends the command to the Fingerprint Sensor GT-521F32 via UART.
Parameters
uart The UART line used.
cmd The Command macro defined in fingerprint.h
param The parameter value required while sending the particular command.
Returns
void.
Definition at line 43 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
Referenced by fp_capture(), fp_close(), fp_deleteall(), fp_enroll(), fp_get_enrollcount(), fp_identify(), fp_isfingerpress(), fp_led_status(), and fp_open().
fp_deleteid()
uint16_t fp_deleteid (uart_t uart, uint16_t id)
This function deletes the specified Fingerprint ID.
Parameters
uart The UART line used.
id The fingerprint ID number.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 258 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), FP_DELETEID_CMD, fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
fp_enroll()
void fp_enroll (uart_t uart, uint8_t enroll_cmd)
This function enrolls the fingerprint.
Parameters
uart The UART line used.
enroll_cmd The Enrollment Command Macro: FP_ENROLL1_CMD, FP_ENROLL2_CMD, FP_ENROLL3_CMD.
Returns
void.
Definition at line 157 of file fingerprint.c.
References FP_BEST_IMAGE, fp_capture(), fp_cmdsend(), fp_isfingerpress(), FP_NOPARAM, fp_responsercv(), and printf.
Referenced by add_fingerprint().
fp_identify()
uint16_t fp_identify (uart_t uart)
This function identifies the captured fingerprint from the stored fingerprints and returns the ID.
Parameters
uart The UARt line used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 324 of file fingerprint.c.
References fp_cmdsend(), FP_IDENTIFY_CMD, FP_NOPARAM, and fp_responsercv().
Referenced by fp_access_handle().
fp_interrupt_config()
void fp_interrupt_config (void)
This function initializes and enables the required GPIO pins interrupts for fingerprint sensor GT-521F32.
Returns
void.
Definition at line 23 of file fingerprint.c.
References fp_interrupt_enable(), FP_IRQ_PIN, FP_IRQ_PORT, and fp_irqhandler().
fp_irqhandler()
void fp_irqhandler (void)
Callback function for Fingerprint Interrupt Handler.
Returns
void.
Definition at line 379 of file fingerprint.c.
References fp_access_handle(), FP_IRQ_PIN, FP_IRQ_PORT, and printf.
Referenced by fp_interrupt_config().
fp_responsercv()
uint16_t fp_responsercv (uart_t uart)
This function receives the response packet from the Fingerprint Sensor GT-521F32 and returns the output parameter/error code.
Parameters
uart The UART line being used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK.
Definition at line 68 of file fingerprint.c.
References ACK, NACK, RESPONSE_SIZE, and temp().
Referenced by fp_baudrate(), fp_capture(), fp_close(), fp_deleteall(), fp_deleteid(), fp_enroll(), fp_get_enrollcount(), fp_identify(), fp_isfingerpress(), fp_led_status(), fp_open(), fp_start_enroll(), and fp_verify().
fp_start_enroll()
uint16_t fp_start_enroll (uart_t uart, uint16_t new_id)
This function Starts the fingerprint Enrollment process.
Parameters
uart The UART lune used.
new_id The ID number for the fingerprint.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 121 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), FP_ENROLLSTART_CMD, fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
Referenced by add_fingerprint().
fp_verify()
uint16_t fp_verify (uart_t uart, uint16_t id)
This function verifies the latest captured fingerprint.
Parameters
uart The UART line used.
id The ID to be compared with.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 291 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), fp_responsercv(), FP_VERIFY_CMD, PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().