inc/fingerprint.h File Reference
Header file for fingerprint.c.
#include `inc/main.h`
#include `inc/myuart.h`
Macros
#define COMMAND_SIZE (12)
#define RESPONSE_SIZE (12)
#define START_CODE1 (0x55)
#define START_CODE2 (0xAA)
#define DEVICEID_LSBYTE (0x01)
#define DEVICEID_MSBYTE (0x00)
#define PARAMETER_BYTES (0x00)
#define CMD_CODE_MSBYTE (0x00)
#define CHECKSUM_BYTES (0x00)
#define FP_OPEN_CMD (0x01)
#define FP_CLOSE_CMD (0x02)
#define FP_BAUDRATE_CMD (0x04)
#define FP_CMOSLED_CMD (0x12)
#define FP_GETENROLLCOUNT_CMD (0x20)
#define FP_CHECKENROLLED_CMD (0x21)
#define FP_ENROLLSTART_CMD (0x22)
#define FP_ENROLL1_CMD (0x23)
#define FP_ENROLL2_CMD (0x24)
#define FP_ENROLL3_CMD (0x25)
#define FP_ISPRESSFINGER_CMD (0x26)
#define FP_DELETEID_CMD (0x40)
#define FP_DELETEALL_CMD (0x41)
#define FP_VERIFY_CMD (0x50)
#define FP_IDENTIFY_CMD (0x51)
#define FP_CAPTUREFINGER_CMD (0x60)
#define FP_GETIMAGE_CMD (0x62)
#define FP_GETRAWIMAGE_CMD (0x63)
#define ACK (0x30)
#define NACK (0x31)
#define FP_LEDON (1)
#define FP_LEDOFF (0)
#define FP_NOEXTRA_INFO (0)
#define FP_NOPARAM (0)
#define FP_BEST_IMAGE (1)
#define FP_LOW_IMAGE (0)
#define FP_FINGER_PRESSED (0)
#define FP_NACK_DB_IS_EMPTY (0x100A)
#define FP_NACK_IDENTIFY_FAILED (0x1008)
#define FP_IRQ_PORT (GPIO_PORTL_BASE)
#define FP_IRQ_PIN (GPIO_PIN_3)
Functions
void fp_interrupt_config (void)
This function initializes and enables the required GPIO pins interrupts for fingerprint sensor GT-521F32.
void fp_cmdsend (uart_t uart, uint8_t cmd, uint8_t param)
This function sends the command to the Fingerprint Sensor GT-521F32 via UART.
uint16_t fp_responsercv (uart_t uart)
This function receives the response packet from the Fingerprint Sensor GT-521F32 and returns the output parameter/error code.
uint16_t fp_checksum_calc (uint8_t packet[])
This function calculates the checksum as specfied in the datasheet of Fingerprint GT-521F32.
uint16_t fp_baudrate (uart_t uart, uint16_t baudrate)
This function changes the baudrate. The default baudrate is 9600.
uint16_t fp_start_enroll (uart_t uart, uint16_t new_id)
This function Starts the fingerprint Enrollment process.
void fp_enroll (uart_t uart, uint8_t enroll_cmd)
This function enrolls the fingerprint.
void add_fingerprint (uart_t uart)
This function adds a fingerprint.
uint16_t fp_deleteid (uart_t uart, uint16_t id)
This function deletes the specified Fingerprint ID.
uint16_t fp_verify (uart_t uart, uint16_t id)
This function verifies the latest captured fingerprint.
uint16_t fp_identify (uart_t uart)
This function identifies the captured fingerprint from the stored fingerprints and returns the ID.
void fp_irqhandler (void)
Callback function for Fingerprint Interrupt Handler.
void fingerprint_test (void)
This function was used for testing purposes.
void fp_init (void)
This function initializes the Scanner and turns LED on.
void fp_interrupt_enable (void)
This function enables the interrupts for fingerprint sensor.
void fp_interrupt_disable (void)
This function disables the interrupts for fingerprint sensor.
uint16_t fp_open (uart_t uart)
This function is used to initialize and get the device's static information.
uint16_t fp_led_status (uart_t uart, uint8_t status)
This function switches the LED on or off.
uint16_t fp_get_enrollcount (uart_t uart)
This function return the Number of Fingerprints enrolled in the Fingerprint Sensor GT-521F32.
uint16_t fp_isfingerpress (uart_t uart)
This function checks whether the finger is pressed against the scanner.
uint16_t fp_capture (uart_t uart, uint8_t resolution)
This function Captures the fingerprint.
uint16_t fp_deleteall (uart_t uart)
This function deletes all the Registered Fingerprints.
uint16_t fp_close (uart_t uart)
This function terminates. Virtually does nothing.
Detailed Description
Header file for fingerprint.c.
The file consists of all the function declarations, macros and typedefs related to Fingerprint functionality. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/19/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
ACK
#define ACK (0x30)
Definition at line 65 of file fingerprint.h.
Referenced by fp_responsercv().
CHECKSUM_BYTES
#define CHECKSUM_BYTES (0x00)
Definition at line 41 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
CMD_CODE_MSBYTE
#define CMD_CODE_MSBYTE (0x00)
Definition at line 40 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
COMMAND_SIZE
#define COMMAND_SIZE (12)
Size of the Command Packet
Definition at line 27 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
DEVICEID_LSBYTE
#define DEVICEID_LSBYTE (0x01)
Definition at line 37 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
DEVICEID_MSBYTE
#define DEVICEID_MSBYTE (0x00)
Definition at line 38 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
FP_BAUDRATE_CMD
#define FP_BAUDRATE_CMD (0x04)
Definition at line 49 of file fingerprint.h.
Referenced by fp_baudrate().
FP_BEST_IMAGE
#define FP_BEST_IMAGE (1)
Parameter Value to get High Resolution Fingerprint Image, Use at the time of enrolling fingerprint
Definition at line 76 of file fingerprint.h.
Referenced by fp_enroll().
FP_CAPTUREFINGER_CMD
#define FP_CAPTUREFINGER_CMD (0x60)
Definition at line 62 of file fingerprint.h.
Referenced by fp_capture().
FP_CHECKENROLLED_CMD
#define FP_CHECKENROLLED_CMD (0x21)
Definition at line 52 of file fingerprint.h.
FP_CLOSE_CMD
#define FP_CLOSE_CMD (0x02)
Definition at line 48 of file fingerprint.h.
Referenced by fp_close().
FP_CMOSLED_CMD
#define FP_CMOSLED_CMD (0x12)
Definition at line 50 of file fingerprint.h.
Referenced by fp_led_status().
FP_DELETEALL_CMD
#define FP_DELETEALL_CMD (0x41)
Definition at line 59 of file fingerprint.h.
Referenced by fp_deleteall().
FP_DELETEID_CMD
#define FP_DELETEID_CMD (0x40)
Definition at line 58 of file fingerprint.h.
Referenced by fp_deleteid().
FP_ENROLL1_CMD
#define FP_ENROLL1_CMD (0x23)
Definition at line 54 of file fingerprint.h.
Referenced by add_fingerprint().
FP_ENROLL2_CMD
#define FP_ENROLL2_CMD (0x24)
Definition at line 55 of file fingerprint.h.
Referenced by add_fingerprint().
FP_ENROLL3_CMD
#define FP_ENROLL3_CMD (0x25)
Definition at line 56 of file fingerprint.h.
Referenced by add_fingerprint().
FP_ENROLLSTART_CMD
#define FP_ENROLLSTART_CMD (0x22)
Definition at line 53 of file fingerprint.h.
Referenced by fp_start_enroll().
FP_FINGER_PRESSED
#define FP_FINGER_PRESSED (0)
Parameter Value in response indicating finger is pressed.
Definition at line 78 of file fingerprint.h.
FP_GETENROLLCOUNT_CMD
#define FP_GETENROLLCOUNT_CMD (0x20)
Definition at line 51 of file fingerprint.h.
Referenced by fp_get_enrollcount().
FP_GETIMAGE_CMD
#define FP_GETIMAGE_CMD (0x62)
Definition at line 63 of file fingerprint.h.
FP_GETRAWIMAGE_CMD
#define FP_GETRAWIMAGE_CMD (0x63)
Definition at line 64 of file fingerprint.h.
FP_IDENTIFY_CMD
#define FP_IDENTIFY_CMD (0x51)
Definition at line 61 of file fingerprint.h.
Referenced by fp_identify().
FP_IRQ_PIN
#define FP_IRQ_PIN (GPIO_PIN_3)
Pin for Fingerprint sensor interrupt
Definition at line 93 of file fingerprint.h.
Referenced by add_fingerprint(), fp_interrupt_config(), fp_interrupt_disable(), fp_interrupt_enable(), and fp_irqhandler().
FP_IRQ_PORT
#define FP_IRQ_PORT (GPIO_PORTL_BASE)
Port for Fingerprint sensor interrupt
Definition at line 92 of file fingerprint.h.
Referenced by add_fingerprint(), fp_interrupt_config(), fp_interrupt_disable(), fp_interrupt_enable(), and fp_irqhandler().
FP_ISPRESSFINGER_CMD
#define FP_ISPRESSFINGER_CMD (0x26)
Definition at line 57 of file fingerprint.h.
Referenced by fp_isfingerpress().
FP_LEDOFF
#define FP_LEDOFF (0)
Parameter Value to switch off the LED
Definition at line 73 of file fingerprint.h.
FP_LEDON
#define FP_LEDON (1)
Parameter Value to switch on the LED
Definition at line 72 of file fingerprint.h.
Referenced by fingerprint_test(), fp_init(), and fp_led_status().
FP_LOW_IMAGE
#define FP_LOW_IMAGE (0)
Parameter Value to get fast but low Resolution Fingerprint Image, Use at the time of verifying fingerprint
Definition at line 77 of file fingerprint.h.
Referenced by fp_access_handle().
FP_NACK_DB_IS_EMPTY
#define FP_NACK_DB_IS_EMPTY (0x100A)
Definition at line 85 of file fingerprint.h.
Referenced by fp_access_handle().
FP_NACK_IDENTIFY_FAILED
#define FP_NACK_IDENTIFY_FAILED (0x1008)
Definition at line 86 of file fingerprint.h.
Referenced by fp_access_handle().
FP_NOEXTRA_INFO
#define FP_NOEXTRA_INFO (0)
Parameter Value for OPEN command
Definition at line 74 of file fingerprint.h.
Referenced by fp_open().
FP_NOPARAM
#define FP_NOPARAM (0)
Parameter Value for no parameter
Definition at line 75 of file fingerprint.h.
Referenced by fp_close(), fp_deleteall(), fp_enroll(), fp_get_enrollcount(), fp_identify(), and fp_isfingerpress().
FP_OPEN_CMD
#define FP_OPEN_CMD (0x01)
Definition at line 47 of file fingerprint.h.
Referenced by fp_open().
FP_VERIFY_CMD
#define FP_VERIFY_CMD (0x50)
Definition at line 60 of file fingerprint.h.
Referenced by fp_verify().
NACK
#define NACK (0x31)
Definition at line 66 of file fingerprint.h.
Referenced by fp_responsercv().
PARAMETER_BYTES
#define PARAMETER_BYTES (0x00)
Definition at line 39 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
RESPONSE_SIZE
#define RESPONSE_SIZE (12)
Size of the Response Packet
Definition at line 28 of file fingerprint.h.
Referenced by fp_responsercv().
START_CODE1
#define START_CODE1 (0x55)
Definition at line 35 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
START_CODE2
#define START_CODE2 (0xAA)
Definition at line 36 of file fingerprint.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
Function Documentation
add_fingerprint()
void add_fingerprint (uart_t uart)
This function adds a fingerprint.
Parameters
uart The UART line used.
Returns
void.
Definition at line 177 of file fingerprint.c.
References fp_enroll(), FP_ENROLL1_CMD, FP_ENROLL2_CMD, FP_ENROLL3_CMD, fp_get_enrollcount(), FP_IRQ_PIN, FP_IRQ_PORT, fp_start_enroll(), and printf.
Referenced by uart_packet_handler().
fingerprint_test()
void fingerprint_test (void)
This function was used for testing purposes.
Returns
void.
Definition at line 400 of file fingerprint.c.
References fp_led_status(), FP_LEDON, fp_open(), and UART_FP.
fp_baudrate()
uint16_t fp_baudrate (uart_t uart, uint16_t baudrate)
This function changes the baudrate. The default baudrate is 9600.
Parameters
uart The UART line used.
baudrate The baudrate MACRO:
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 225 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, FP_BAUDRATE_CMD, fp_checksum_calc(), fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
fp_capture()
uint16_t fp_capture (uart_t uart, uint8_t resolution) [inline]
This function Captures the fingerprint.
Parameters
uart The UART line used.
resolution The resolution for the fingerprint scan. The macros are: FP_BEST_IMAGE, FP_LOW_IMAGE.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 302 of file fingerprint.h.
References FP_CAPTUREFINGER_CMD, fp_cmdsend(), and fp_responsercv().
Referenced by fp_access_handle(), and fp_enroll().
fp_checksum_calc()
uint16_t fp_checksum_calc (uint8_t packet[])
This function calculates the checksum as specfied in the datasheet of Fingerprint GT-521F32.
Parameters
packet The Response/Command packet array as per the datasheet of GT-521F32.
Returns
uint16_t The calculated checksum value.
Definition at line 108 of file fingerprint.c.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), and fp_verify().
fp_close()
uint16_t fp_close (uart_t uart) [inline]
This function terminates. Virtually does nothing.
Returns
uint16_t The error code or output parameter in case of NACK/ACK.
Definition at line 326 of file fingerprint.h.
References FP_CLOSE_CMD, fp_cmdsend(), FP_NOPARAM, and fp_responsercv().
fp_cmdsend()
void fp_cmdsend (uart_t uart, uint8_t cmd, uint8_t param)
This function sends the command to the Fingerprint Sensor GT-521F32 via UART.
Parameters
uart The UART line used.
cmd The Command macro defined in fingerprint.h
param The parameter value required while sending the particular command.
Returns
void.
Definition at line 43 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
Referenced by fp_capture(), fp_close(), fp_deleteall(), fp_enroll(), fp_get_enrollcount(), fp_identify(), fp_isfingerpress(), fp_led_status(), and fp_open().
fp_deleteall()
uint16_t fp_deleteall (uart_t uart) [inline]
This function deletes all the Registered Fingerprints.
Parameters
uart The UART line used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 315 of file fingerprint.h.
References fp_cmdsend(), FP_DELETEALL_CMD, FP_NOPARAM, and fp_responsercv().
Referenced by uart_packet_handler().
fp_deleteid()
uint16_t fp_deleteid (uart_t uart, uint16_t id)
This function deletes the specified Fingerprint ID.
Parameters
uart The UART line used.
id The fingerprint ID number.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 258 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), FP_DELETEID_CMD, fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
fp_enroll()
void fp_enroll (uart_t uart, uint8_t enroll_cmd)
This function enrolls the fingerprint.
Parameters
uart The UART line used.
enroll_cmd The Enrollment Command Macro: FP_ENROLL1_CMD, FP_ENROLL2_CMD, FP_ENROLL3_CMD.
Returns
void.
Definition at line 157 of file fingerprint.c.
References FP_BEST_IMAGE, fp_capture(), fp_cmdsend(), fp_isfingerpress(), FP_NOPARAM, fp_responsercv(), and printf.
Referenced by add_fingerprint().
fp_get_enrollcount()
uint16_t fp_get_enrollcount (uart_t uart) [inline]
This function return the Number of Fingerprints enrolled in the Fingerprint Sensor GT-521F32.
Parameters
uart The UARt line used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 273 of file fingerprint.h.
References fp_cmdsend(), FP_GETENROLLCOUNT_CMD, FP_NOPARAM, fp_responsercv(), and printf.
Referenced by add_fingerprint().
fp_identify()
uint16_t fp_identify (uart_t uart)
This function identifies the captured fingerprint from the stored fingerprints and returns the ID.
Parameters
uart The UARt line used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 324 of file fingerprint.c.
References fp_cmdsend(), FP_IDENTIFY_CMD, FP_NOPARAM, and fp_responsercv().
Referenced by fp_access_handle().
fp_init()
void fp_init (void) [inline]
This function initializes the Scanner and turns LED on.
Returns
void.
Definition at line 214 of file fingerprint.h.
References fp_led_status(), FP_LEDON, fp_open(), and UART_FP.
fp_interrupt_config()
void fp_interrupt_config (void)
This function initializes and enables the required GPIO pins interrupts for fingerprint sensor GT-521F32.
Returns
void.
Definition at line 23 of file fingerprint.c.
References fp_interrupt_enable(), FP_IRQ_PIN, FP_IRQ_PORT, and fp_irqhandler().
fp_interrupt_disable()
void fp_interrupt_disable (void) [inline]
This function disables the interrupts for fingerprint sensor.
Returns
void.
Definition at line 236 of file fingerprint.h.
References FP_IRQ_PIN, and FP_IRQ_PORT.
Referenced by uart_packet_handler().
fp_interrupt_enable()
void fp_interrupt_enable (void) [inline]
This function enables the interrupts for fingerprint sensor.
Returns
void.
Definition at line 225 of file fingerprint.h.
References FP_IRQ_PIN, and FP_IRQ_PORT.
Referenced by fp_interrupt_config(), timer1handler(), and uart_packet_handler().
fp_irqhandler()
void fp_irqhandler (void)
Callback function for Fingerprint Interrupt Handler.
Returns
void.
Definition at line 379 of file fingerprint.c.
References fp_access_handle(), FP_IRQ_PIN, FP_IRQ_PORT, and printf.
Referenced by fp_interrupt_config().
fp_isfingerpress()
uint16_t fp_isfingerpress (uart_t uart) [inline]
This function checks whether the finger is pressed against the scanner.
Parameters
uart The UART line used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 289 of file fingerprint.h.
References fp_cmdsend(), FP_ISPRESSFINGER_CMD, FP_NOPARAM, and fp_responsercv().
Referenced by fp_enroll().
fp_led_status()
uint16_t fp_led_status (uart_t uart, uint8_t status) [inline]
This function switches the LED on or off.
Parameters
uart The UART line used.
status The FP_LEDON or FP_LEDOFF Macro to switch the LED on or off.
Returns
uint16_t The error code or output parameter in case of NACK/ACK.
Definition at line 260 of file fingerprint.h.
References fp_cmdsend(), FP_CMOSLED_CMD, FP_LEDON, fp_responsercv(), and UART_FP.
Referenced by fingerprint_test(), and fp_init().
fp_open()
uint16_t fp_open (uart_t uart) [inline]
This function is used to initialize and get the device's static information.
Returns
uint16_t The error code or output parameter in case of NACK/ACK.
Definition at line 247 of file fingerprint.h.
References fp_cmdsend(), FP_NOEXTRA_INFO, FP_OPEN_CMD, and fp_responsercv().
Referenced by fingerprint_test(), and fp_init().
fp_responsercv()
uint16_t fp_responsercv (uart_t uart)
This function receives the response packet from the Fingerprint Sensor GT-521F32 and returns the output parameter/error code.
Parameters
uart The UART line being used.
Returns
uint16_t The error code or output parameter in case of NACK/ACK.
Definition at line 68 of file fingerprint.c.
References ACK, NACK, RESPONSE_SIZE, and temp().
Referenced by fp_baudrate(), fp_capture(), fp_close(), fp_deleteall(), fp_deleteid(), fp_enroll(), fp_get_enrollcount(), fp_identify(), fp_isfingerpress(), fp_led_status(), fp_open(), fp_start_enroll(), and fp_verify().
fp_start_enroll()
uint16_t fp_start_enroll (uart_t uart, uint16_t new_id)
This function Starts the fingerprint Enrollment process.
Parameters
uart The UART lune used.
new_id The ID number for the fingerprint.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 121 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), FP_ENROLLSTART_CMD, fp_responsercv(), PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().
Referenced by add_fingerprint().
fp_verify()
uint16_t fp_verify (uart_t uart, uint16_t id)
This function verifies the latest captured fingerprint.
Parameters
uart The UART line used.
id The ID to be compared with.
Returns
uint16_t The error code or output parameter in case of NACK/ACK respectively.
Definition at line 291 of file fingerprint.c.
References CHECKSUM_BYTES, CMD_CODE_MSBYTE, COMMAND_SIZE, DEVICEID_LSBYTE, DEVICEID_MSBYTE, fp_checksum_calc(), fp_responsercv(), FP_VERIFY_CMD, PARAMETER_BYTES, START_CODE1, START_CODE2, and uart_busy().