src/keypad.c File Reference
This file consists of all the functions required for the Keypad.
#include `inc/keypad.h`
#include `inc/delay.h`
#include `inc/myuart.h`
#include `inc/lcd.h`
#include `inc/packet.h`
Functions
void keypad_config (void)
This function initializes GPIOs and the required interrupts.
void keypad_interrupt_enable (void)
Enable Interrupts for Keypad Functionality.
void keypad_interrupt_disable (void)
Disable Interrupts for Keypad Functionality.
void column_handler (void)
Callback function of Column 1 Interrupt.
void keypad_button_detect (uint32_t column_port, uint32_t column_pin, char keypad_digits[ROWS][COLUMNS], uint8_t column)
This function detects which key is pressed.
Variables
char keypad_digits [ROWS][COLUMNS] = {{'1','2','3','A'},{'4','5','6','B'},{'7','8','9','C'},{'*','0','#','D'}}
Detailed Description
This file consists of all the functions required for the Keypad.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/19/2019
Copyright
Copyright (c) 2019
Function Documentation
column_handler()
void column_handler (void)
Callback function of Column 1 Interrupt.
Returns
void.
Definition at line 92 of file keypad.c.
References COLUMN1, COLUMN1_PIN, COLUMN1_PORT, COLUMN2, COLUMN2_PIN, COLUMN2_PORT, COLUMN3, COLUMN3_PIN, COLUMN3_PORT, COLUMN4, COLUMN4_PIN, COLUMN4_PORT, COMMON_COLUMN_PORT, delay_ms(), keypad_button_detect(), keypad_digits, LCD_write(), otp_arr, otp_count, otp_flag, OTP_SEND_BBG_ID, packet_make(), packet_send_uart(), printf, TRUE, and UART_BBG.
Referenced by keypad_config().
keypad_button_detect()
void keypad_button_detect (uint32_t column_port, uint32_t column_pin, char keypad_digits[ROWS][COLUMNS], uint8_t column)
This function detects which key is pressed.
Parameters
column_port The Column Port being checked.
column_pin The Column Pin being checked.
keypad_digits The array storing character data.
column The column being examined.
Returns
void.
Definition at line 166 of file keypad.c.
References keypad_digits, lcd_write_data(), otp_arr, otp_count, printf, ROW1_PIN, ROW1_PORT, ROW2_PIN, ROW2_PORT, ROW3_PIN, ROW3_PORT, ROW4_PIN, and ROW4_PORT.
Referenced by column_handler().
keypad_config()
void keypad_config (void)
This function initializes GPIOs and the required interrupts.
Returns
void.
Definition at line 26 of file keypad.c.
References COLUMN1_PIN, COLUMN1_PORT, COLUMN2_PIN, COLUMN2_PORT, COLUMN3_PIN, COLUMN3_PORT, COLUMN4_PIN, COLUMN4_PORT, column_handler(), COMMON_COLUMN_PORT, ROW1_PIN, ROW1_PORT, ROW2_PIN, ROW2_PORT, ROW3_PIN, ROW3_PORT, ROW4_PIN, and ROW4_PORT.
keypad_interrupt_disable()
void keypad_interrupt_disable (void)
Disable Interrupts for Keypad Functionality.
Returns
void.
Definition at line 82 of file keypad.c.
References COLUMN1_PIN, COLUMN1_PORT, COLUMN2_PIN, COLUMN2_PORT, COLUMN3_PIN, COLUMN3_PORT, COLUMN4_PIN, and COLUMN4_PORT.
keypad_interrupt_enable()
void keypad_interrupt_enable (void)
Enable Interrupts for Keypad Functionality.
Returns
void.
Definition at line 72 of file keypad.c.
References COLUMN1_PIN, COLUMN1_PORT, COLUMN2_PIN, COLUMN2_PORT, COLUMN3_PIN, COLUMN3_PORT, COLUMN4_PIN, and COLUMN4_PORT.
Referenced by uart_packet_handler().
Variable Documentation
keypad_digits
char keypad_digits[ROWS][COLUMNS] = {{'1','2','3','A'},{'4','5','6','B'},{'7','8','9','C'},{'*','0','#','D'}}
Definition at line 24 of file keypad.c.
Referenced by column_handler(), and keypad_button_detect().