inc/lcd.h File Reference
Header file for lcd.c.
#include `inc/main.h`
Macros
#define D4 GPIO_PIN_0
#define D5 GPIO_PIN_1
#define D6 GPIO_PIN_2
#define D7 GPIO_PIN_3
#define CLEAR_DISPLAY (0x01)
#define SET_4_BIT (0x02)
#define DISPLAY_ON (0x0E)
#define LCD_SET_2_LINES (0x28)
#define LCD_INCREMENT (0x06)
#define RS GPIO_PIN_4
#define RW GPIO_PIN_5
#define E GPIO_PIN_6
#define ALL_CMD_PINS E|RW|RS
#define ALL_DATA_PINS D7|D6|D5|D4
Functions
void lcd_init ()
void lcd_write_data (uint8_t)
void lcd_write_cmd (uint8_t)
void LCD_write (char *)
void lcd_goto (uint8_t addr)
void lcdgotoxy (uint8_t row, uint8_t column)
uint8_t lcd_read_address (void)
void lcd_test (void)
void lcd_clear (void)
Detailed Description
Header file for lcd.c.
The file consists of all the function declarations, macros and typedefs related to LCD functionality. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Satya Mehta
Date
04/20/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
ALL_CMD_PINS
#define ALL_CMD_PINS E|RW|RS
Definition at line 38 of file lcd.h.
Referenced by lcd_init().
ALL_DATA_PINS
#define ALL_DATA_PINS D7|D6|D5|D4
Definition at line 39 of file lcd.h.
Referenced by lcd_init(), lcd_read_address(), lcd_write_cmd(), and lcd_write_data().
CLEAR_DISPLAY
#define CLEAR_DISPLAY (0x01)
Definition at line 29 of file lcd.h.
Referenced by lcd_clear(), lcd_init(), and LCD_write().
D4
#define D4 GPIO_PIN_0
Definition at line 24 of file lcd.h.
D5
#define D5 GPIO_PIN_1
Definition at line 25 of file lcd.h.
D6
#define D6 GPIO_PIN_2
Definition at line 26 of file lcd.h.
D7
#define D7 GPIO_PIN_3
Definition at line 27 of file lcd.h.
DISPLAY_ON
#define DISPLAY_ON (0x0E)
Definition at line 31 of file lcd.h.
Referenced by lcd_init().
E
#define E GPIO_PIN_6
Definition at line 37 of file lcd.h.
Referenced by lcd_init(), lcd_read_address(), lcd_write_cmd(), and lcd_write_data().
LCD_INCREMENT
#define LCD_INCREMENT (0x06)
Definition at line 33 of file lcd.h.
Referenced by lcd_init().
LCD_SET_2_LINES
#define LCD_SET_2_LINES (0x28)
Definition at line 32 of file lcd.h.
Referenced by lcd_init().
RS
#define RS GPIO_PIN_4
Definition at line 35 of file lcd.h.
Referenced by lcd_init(), lcd_read_address(), lcd_write_cmd(), and lcd_write_data().
RW
#define RW GPIO_PIN_5
Definition at line 36 of file lcd.h.
Referenced by lcd_read_address(), lcd_write_cmd(), and lcd_write_data().
SET_4_BIT
#define SET_4_BIT (0x02)
Definition at line 30 of file lcd.h.
Referenced by lcd_init().
Function Documentation
lcd_clear()
void lcd_clear (void) [inline]
Definition at line 55 of file lcd.h.
References CLEAR_DISPLAY, and lcd_write_cmd().
lcd_goto()
void lcd_goto (uint8_t addr)
Definition at line 95 of file lcd.c.
References lcd_write_cmd().
Referenced by lcdgotoxy().
lcd_init()
void lcd_init ()
Definition at line 17 of file lcd.c.
References ALL_CMD_PINS, ALL_DATA_PINS, CLEAR_DISPLAY, DISPLAY_ON, E, LCD_INCREMENT, LCD_SET_2_LINES, lcd_write_cmd(), RS, and SET_4_BIT.
lcd_read_address()
uint8_t lcd_read_address (void)
Definition at line 106 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
lcd_test()
void lcd_test (void)
Definition at line 128 of file lcd.c.
References LCD_write().
LCD_write()
void LCD_write (char *)
Definition at line 73 of file lcd.c.
References CLEAR_DISPLAY, lcd_write_cmd(), and lcd_write_data().
Referenced by column_handler(), fp_access_handle(), lcd_test(), timer1handler(), and uart_packet_handler().
lcd_write_cmd()
void lcd_write_cmd (uint8_t)
Definition at line 43 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
Referenced by lcd_clear(), lcd_goto(), lcd_init(), and LCD_write().
lcd_write_data()
void lcd_write_data (uint8_t)
Definition at line 58 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
Referenced by keypad_button_detect(), and LCD_write().
lcdgotoxy()
void lcdgotoxy (uint8_t row, uint8_t column)
Definition at line 100 of file lcd.c.
References lcd_goto(), and row_address.