src/lcd.c File Reference
This file consists of all the functions required for the LCD.
#include `inc/lcd.h`
Functions
void lcd_init ()
void lcd_write_cmd (uint8_t command)
void lcd_write_data (uint8_t data)
void LCD_write (char *string)
void lcd_goto (uint8_t addr)
void lcdgotoxy (uint8_t row, uint8_t column)
uint8_t lcd_read_address (void)
void lcd_test (void)
Variables
uint8_t row_address [4] = {0x00, 0x40, 0x10, 0x50}
Detailed Description
This file consists of all the functions required for the LCD.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/20/2019
Copyright
Copyright (c) 2019
Function Documentation
lcd_goto()
void lcd_goto (uint8_t addr)
Definition at line 95 of file lcd.c.
References lcd_write_cmd().
Referenced by lcdgotoxy().
lcd_init()
void lcd_init ()
Definition at line 17 of file lcd.c.
References ALL_CMD_PINS, ALL_DATA_PINS, CLEAR_DISPLAY, DISPLAY_ON, E, LCD_INCREMENT, LCD_SET_2_LINES, lcd_write_cmd(), RS, and SET_4_BIT.
lcd_read_address()
uint8_t lcd_read_address (void)
Definition at line 106 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
lcd_test()
void lcd_test (void)
Definition at line 128 of file lcd.c.
References LCD_write().
LCD_write()
void LCD_write (char * string)
Definition at line 73 of file lcd.c.
References CLEAR_DISPLAY, lcd_write_cmd(), and lcd_write_data().
Referenced by column_handler(), fp_access_handle(), lcd_test(), timer1handler(), and uart_packet_handler().
lcd_write_cmd()
void lcd_write_cmd (uint8_t command)
Definition at line 43 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
Referenced by lcd_clear(), lcd_goto(), lcd_init(), and LCD_write().
lcd_write_data()
void lcd_write_data (uint8_t data)
Definition at line 58 of file lcd.c.
References ALL_DATA_PINS, E, RS, and RW.
Referenced by keypad_button_detect(), and LCD_write().
lcdgotoxy()
void lcdgotoxy (uint8_t row, uint8_t column)
Definition at line 100 of file lcd.c.
References lcd_goto(), and row_address.
Variable Documentation
row_address
uint8_t row_address[4] = {0x00, 0x40, 0x10, 0x50}
Definition at line 16 of file lcd.c.
Referenced by lcdgotoxy().