src/logger.c File Reference
This file consists of all the functions required for logging data to the host console.
#include `inc/logger.h`
#include `inc/sync_objects.h`
#include `inc/msg_queue.h`
Functions
uint8_t nrf_loggertask_init (void)
The function creates the Logger Task.
void nrf_log (void)
This function receives all the data from other tasks via message queues and logs the data to the host console.
static void nrf_logger (void *pvParameters)
Detailed Description
This file consists of all the functions required for logging data to the host console.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/13/2019
Copyright
Copyright (c) 2019
Function Documentation
nrf_log()
void nrf_log (void)
This function receives all the data from other tasks via message queues and logs the data to the host console.
Returns
void.
Definition at line 34 of file logger.c.
References g_uartsem, LED_RCV_ID, nrf_log_mq, RANDOM_TEST_ID, and TEMP_RCV_ID.
Referenced by nrf_logger().
nrf_logger()
static void nrf_logger (void * pvParameters) [static]
Definition at line 91 of file logger.c.
References nrf_log().
Referenced by nrf_loggertask_init().
nrf_loggertask_init()
uint8_t nrf_loggertask_init (void)
The function creates the Logger Task.
Returns
uint8_t Returns if the Task initialization is successful.
Definition at line 21 of file logger.c.
References LEDTASKSTACKSIZE, and nrf_logger().