inc/myuart.h File Reference
Header file for myuart.c.
#include `inc/main.h`
Macros
#define BAUDRATE_FP (9600)
Enumerations
enum uart_t {
UART0 = UART0_BASE,
UART1 = UART1_BASE,
UART_FP = UART2_BASE,
UART3 = UART3_BASE,
UART4 = UART4_BASE,
UART5 = UART5_BASE,
UART_BBG = UART6_BASE,
UART7 = UART7_BASE
 }
Functions
void uart_configure (uart_t uart, uint32_t clock, uint32_t baudrate, bool irq)
Configures the Particular UART required.
void uart_comm_flushRX (uart_t uart)
This function flushes the UART RX FIFO.
void uart_comm_flushTX (uart_t uart)
This function flushes the UART TX FIFO.
void uart_send (uart_t uart, uint8_t value)
This function sends data over UART.
void uart_busy (uart_t uart)
This function checks is the specified UART line is busy and waits till it is free.
Detailed Description
Header file for myuart.c.
The file consists of all the function declarations, macros and datatype declarations required for UART Communication. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/22/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
BAUDRATE_FP
#define BAUDRATE_FP (9600)
Definition at line 24 of file myuart.h.
Enumeration Type Documentation
uart_t
enum uart_t
Enumerator
UART0
UART1
UART_FP
UART3
UART4
UART5
UART_BBG
UART7
Definition at line 31 of file myuart.h.
Function Documentation
uart_busy()
void uart_busy (uart_t uart) [inline]
This function checks is the specified UART line is busy and waits till it is free.
Parameters
uart The UART line used.
Returns
void.
Definition at line 96 of file myuart.h.
Referenced by fp_baudrate(), fp_cmdsend(), fp_deleteid(), fp_start_enroll(), fp_verify(), and uart_send().
uart_comm_flushRX()
void uart_comm_flushRX (uart_t uart)
This function flushes the UART RX FIFO.
Parameters
uart The UART line used.
Returns
void.
Definition at line 69 of file myuart.c.
Referenced by configureUART_bbg().
uart_comm_flushTX()
void uart_comm_flushTX (uart_t uart)
This function flushes the UART TX FIFO.
Parameters
uart The UART line used.
Returns
void.
Note
The UART needs to be enabled again after using this function for the UART to function again.
See also
UARTEnable().
Definition at line 94 of file myuart.c.
Referenced by configureUART_bbg().
uart_configure()
void uart_configure (uart_t uart, uint32_t clock, uint32_t baudrate, bool irq)
Configures the Particular UART required.
Parameters
uart The UART line used.
clock The clock used for the peripheral. The macro is defined is CLOCK IN main.h.
baudrate The baudrate defined for the peripheral.
irq = TRUE: interrupt functionality enabled for UART, FALSE: Interrupt functionality disabled.
Returns
void.
Definition at line 16 of file myuart.c.
References UART_FP.
uart_send()
void uart_send (uart_t uart, uint8_t value)
This function sends data over UART.
Parameters
uart The UART line being used.
value The value to be sent on UART.
Returns
void.
Definition at line 61 of file myuart.c.
References uart_busy().
Referenced by packet_send_uart(), and uart_bbg_test().