src/myuart.c File Reference
This file consists of all the functions required for UART initialization, enable and send/receive functions.
#include `inc/myuart.h`
Functions
void uart_configure (uart_t uart, uint32_t clock, uint32_t baudrate, bool irq)
Configures the Particular UART required.
void uart_send (uart_t uart, uint8_t value)
This function sends data over UART.
void uart_comm_flushRX (uart_t uart)
This function flushes the UART RX FIFO.
void uart_comm_flushTX (uart_t uart)
This function flushes the UART TX FIFO.
Detailed Description
This file consists of all the functions required for UART initialization, enable and send/receive functions.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/22/2019
Copyright
Copyright (c) 2019
Function Documentation
uart_comm_flushRX()
void uart_comm_flushRX (uart_t uart)
This function flushes the UART RX FIFO.
Parameters
uart The UART line used.
Returns
void.
Definition at line 69 of file myuart.c.
Referenced by configureUART_bbg().
uart_comm_flushTX()
void uart_comm_flushTX (uart_t uart)
This function flushes the UART TX FIFO.
Parameters
uart The UART line used.
Returns
void.
Note
The UART needs to be enabled again after using this function for the UART to function again.
See also
UARTEnable().
Definition at line 94 of file myuart.c.
Referenced by configureUART_bbg().
uart_configure()
void uart_configure (uart_t uart, uint32_t clock, uint32_t baudrate, bool irq)
Configures the Particular UART required.
Parameters
uart The UART line used.
clock The clock used for the peripheral. The macro is defined is CLOCK IN main.h.
baudrate The baudrate defined for the peripheral.
irq = TRUE: interrupt functionality enabled for UART, FALSE: Interrupt functionality disabled.
Returns
void.
Definition at line 16 of file myuart.c.
References UART_FP.
uart_send()
void uart_send (uart_t uart, uint8_t value)
This function sends data over UART.
Parameters
uart The UART line being used.
value The value to be sent on UART.
Returns
void.
Definition at line 61 of file myuart.c.
References uart_busy().
Referenced by packet_send_uart(), and uart_bbg_test().