src/nrf_driver.c File Reference
This file consists of all the functions required for NRF24L01+ driver.
#include `inc/nrf_driver.h`
Functions
void nrf_gpio_init (void)
This function initializes all the GPIOs required by the NRF25L01+.
void nrf_interrupt_enable (void)
This function configures and enables the GPIO interrupt for NRF24L01+.
void nrf_write_reg (spi_t spi, uint8_t reg, uint8_t value)
This function writes to a register in the NRF24L01+.
uint8_t nrf_read_reg (spi_t spi, uint8_t reg)
This function reads the value from the register specified by the parameter reg.
void nrf_config (void)
This function configures the register value for NRF24L01+.
void nrf_config_mode (spi_t spi, modes_t mode)
This function configures the NRF24L01+ in TX or RX Mode.
void nrf_packet_send (spi_t spi)
This function sends the packet data.
void nrf_packet_rcv (spi_t spi)
This function receives the packet data.
void nrf_write_TXaddr (spi_t spi, TX addr)
This function assigns the specified TX pipe address.
void nrf_read_TXaddr (spi_t spi)
This function reads the specified TX Pipe address.
void nrf_write_RXaddr (spi_t spi, uint8_t reg, RX addr)
This function assigns the specified RX pipe address.
void nrf_read_RXaddr (spi_t spi, uint8_t reg)
This function reads the specified RX pipe address.
void nrf_irqhandler (void)
Callback Function for NRF24L01+ Interrupt.
Detailed Description
This file consists of all the functions required for NRF24L01+ driver.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/12/2019
Copyright
Copyright (c) 2019
Function Documentation
nrf_config()
void nrf_config (void)
This function configures the register value for NRF24L01+.
Returns
void.
Definition at line 88 of file nrf_driver.c.
References mode_tx, nrf_config_mode(), NRF_ENABLE_RXPIPE_ADDRESS_REG, nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), NRF_RX_ADDR_P0_REG, NRF_RX_BYTES_P0_REG, nrf_write_reg(), nrf_write_RXaddr(), nrf_write_TXaddr(), printf, R_REGISTER_CMD, RX::rx_pipe_address, SPI2, TX::tx_pipe_address, and W_REGISTER_CMD.
nrf_config_mode()
void nrf_config_mode (spi_t spi, modes_t mode)
This function configures the NRF24L01+ in TX or RX Mode.
Parameters
spi The SPI line used.
mode The mode specified by the user.
Definition at line 190 of file nrf_driver.c.
References ce_status(), FLUSH_RX_CMD, FLUSH_TX_CMD, HIGH, mode_rx, mode_tx, NRF_CONFIG_REG, NRF_EN_AA_REG, nrf_packet_send(), nrf_read_reg(), nrf_write_cmd(), nrf_write_reg(), printf, R_REGISTER_CMD, SPI2, and W_REGISTER_CMD.
Referenced by nrf_config().
nrf_gpio_init()
void nrf_gpio_init (void)
This function initializes all the GPIOs required by the NRF25L01+.
The Pins are: Chip Enable, Chip Select and IRQ pin.
Returns
void
Definition at line 18 of file nrf_driver.c.
References NRF_CHIP_ENABLE_PIN, NRF_CHIP_ENABLE_PORT, NRF_CHIP_SELECT_PIN, NRF_CHIP_SELECT_PORT, and nrf_interrupt_enable().
nrf_interrupt_enable()
void nrf_interrupt_enable (void)
This function configures and enables the GPIO interrupt for NRF24L01+.
Returns
void.
Definition at line 37 of file nrf_driver.c.
References NRF_IRQ_PIN, NRF_IRQ_PORT, and nrf_irqhandler().
Referenced by nrf_gpio_init().
nrf_irqhandler()
void nrf_irqhandler (void)
Callback Function for NRF24L01+ Interrupt.
This function is called whenever there is an interrupt on the IRQ pin of NRF24L01+. The interrupt is due to data received and transmitted.
Returns
void.
Definition at line 369 of file nrf_driver.c.
References NRF_IRQ_PORT, NRF_MAX_RT_MASK, nrf_packet_rcv(), nrf_read_reg(), NRF_RX_DR_MASK, NRF_STATUS_REG, NRF_TX_DS_MASK, nrf_write_reg(), printf, R_REGISTER_CMD, R_RX_PAYLOD_CMD, SPI2, spi_dummy_transfer(), spi_transfer(), and W_REGISTER_CMD.
Referenced by nrf_interrupt_enable().
nrf_packet_rcv()
void nrf_packet_rcv (spi_t spi)
This function receives the packet data.
Parameters
spi The SPI line used.
Definition at line 281 of file nrf_driver.c.
References csn_status(), HIGH, LOW, printf, R_RX_PAYLOD_CMD, SPI2, and spi_transfer().
Referenced by nrf_irqhandler().
nrf_packet_send()
void nrf_packet_send (spi_t spi)
This function sends the packet data.
Parameters
spi The SPI line used.
Definition at line 248 of file nrf_driver.c.
References csn_status(), HIGH, LOW, spi_transfer(), and W_TX_PAYLOD_CMD.
Referenced by nrf_config_mode().
nrf_read_reg()
uint8_t nrf_read_reg (spi_t spi, uint8_t reg)
This function reads the value from the register specified by the parameter reg.
Parameters
spi The SPI line used.
reg The Register value to read data from.
Returns
uint8_t The value read from the register reg.
Definition at line 73 of file nrf_driver.c.
References csn_status(), HIGH, LOW, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config(), nrf_config_mode(), and nrf_irqhandler().
nrf_read_RXaddr()
void nrf_read_RXaddr (spi_t spi, uint8_t reg)
This function reads the specified RX pipe address.
Parameters
spi The SPI line used.
reg The Register address of the PIPE.
Definition at line 350 of file nrf_driver.c.
References csn_status(), HIGH, LOW, printf, R_REGISTER_CMD, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config().
nrf_read_TXaddr()
void nrf_read_TXaddr (spi_t spi)
This function reads the specified TX Pipe address.
Parameters
spi The SPI line used.
Definition at line 315 of file nrf_driver.c.
References csn_status(), HIGH, LOW, NRF_TX_ADDR_REG, printf, R_REGISTER_CMD, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config().
nrf_write_reg()
void nrf_write_reg (spi_t spi, uint8_t reg, uint8_t value)
This function writes to a register in the NRF24L01+.
Parameters
spi The SPI line used.
reg The Register value to write to.
value The value to write to the Register.
Returns
void.
Definition at line 60 of file nrf_driver.c.
References csn_status(), HIGH, LOW, and spi_transfer().
Referenced by nrf_config(), nrf_config_mode(), and nrf_irqhandler().
nrf_write_RXaddr()
void nrf_write_RXaddr (spi_t spi, uint8_t reg, RX addr)
This function assigns the specified RX pipe address.
Parameters
spi The SPI line used.
reg The Register address of the PIPE.
addr The object of structure RX.
Definition at line 333 of file nrf_driver.c.
References csn_status(), HIGH, LOW, RX::rx_pipe_address, spi_transfer(), and W_REGISTER_CMD.
Referenced by nrf_config().
nrf_write_TXaddr()
void nrf_write_TXaddr (spi_t spi, TX addr)
This function assigns the specified TX pipe address.
Parameters
spi The SPI line used
addr The object of structure TX.
Definition at line 299 of file nrf_driver.c.
References csn_status(), HIGH, LOW, NRF_TX_ADDR_REG, spi_transfer(), TX::tx_pipe_address, and W_REGISTER_CMD.
Referenced by nrf_config().