inc/nrf_driver.h File Reference
Header file for nrf_driver.c.
#include `inc/main.h`
#include `inc/spi.h`
Classes
struct TX
struct RX
Macros
#define NRF_SEND
#define LOW (0)
#define HIGH (1)
#define SHIFT(y) (1<<y)
#define NRF_CHIP_ENABLE_PORT (GPIO_PORTC_BASE)
#define NRF_CHIP_ENABLE_PIN (GPIO_PIN_7)
#define NRF_CHIP_SELECT_PORT (GPIO_PORTC_BASE)
#define NRF_CHIP_SELECT_PIN (GPIO_PIN_6)
#define NRF_IRQ_PORT (GPIO_PORTL_BASE)
#define NRF_IRQ_PIN (GPIO_PIN_2)
#define NRF_PORT (GPIO_PORTD_BASE)
#define NRF_CLK_PORT (GPIO_PORTD_BASE)
#define NRF_CLK_PIN (GPIO_PIN_3)
#define NRF_FSS_PORT (GPIO_PORTD_BASE)
#define NRF_FSS_PIN (GPIO_PIN_2)
#define NRF_MOSI_PORT (GPIO_PORTD_BASE)
#define NRF_MOSI_PIN (GPIO_PIN_0)
#define NRF_MISO_PORT (GPIO_PORTD_BASE)
#define NRF_MISO_PIN (GPIO_PIN_1)
#define READ_MASK (0xFF)
#define WRITE MASK (0x20)
#define NRF_CONFIG_REG (0x00)
#define NRF_EN_AA_REG (0x01)
#define NRF_ENABLE_RXPIPE_ADDRESS_REG (0x02)
#define NRF_SETUP_AW_REG (0x03)
#define NRF_SETUP_RETR_REG (0x04)
#define NRF_SETUP_RFCHANNEL_REG (0x05)
#define NRF_RFSETUP_REG (0x06)
#define NRF_STATUS_REG (0x07)
#define NRF_RX_ADDR_P0_REG (0x0A)
#define NRF_RX_ADDR_P1_REG (0x0B)
#define NRF_RX_ADDR_P2_REG (0x0C)
#define NRF_RX_ADDR_P3_REG (0x0D)
#define NRF_RX_ADDR_P4_REG (0x0E)
#define NRF_RX_ADDR_P5_REG (0x0F)
#define NRF_TX_ADDR_REG (0x10)
#define NRF_RX_BYTES_P0_REG (0x11)
#define NRF_RX_BYTES_P1_REG (0x12)
#define NRF_RX_BYTES_P2_REG (0x13)
#define NRF_RX_BYTES_P3_REG (0x14)
#define NRF_RX_BYTES_P4_REG (0x15)
#define NRF_RX_BYTES_P5_REG (0x16)
#define NRF_FIFO_STATUS_REG (0x17)
#define RF_DR_LOW250 (5)
#define MASK_RX_DR (0b01000000)
#define RF_DR_LOW (0b00100000)
#define NRF_RX_DR_MASK (0x40)
#define NRF_TX_DS_MASK (0x20)
#define NRF_MAX_RT_MASK (0x10)
#define R_REGISTER_CMD(y) (0x1F & y)
#define W_REGISTER_CMD(y) (0x20 | y)
#define NOP_CMD (0xFF)
#define FLUSH_TX_CMD (0xE1)
#define FLUSH_RX_CMD (0xE2)
#define R_RX_PAYLOD_CMD (0x61)
#define W_TX_PAYLOD_CMD (0xA0)
Enumerations
enum modes_t { mode_tx = 1,
mode_rx = 2
 }
Functions
void nrf_gpio_init (void)
This function initializes all the GPIOs required by the NRF25L01+.
void nrf_interrupt_enable (void)
This function configures and enables the GPIO interrupt for NRF24L01+.
void nrf_write_reg (spi_t spi, uint8_t reg, uint8_t value)
This function writes to a register in the NRF24L01+.
uint8_t nrf_read_reg (spi_t spi, uint8_t reg)
This function reads the value from the register specified by the parameter reg.
void nrf_config (void)
This function configures the register value for NRF24L01+.
void nrf_config_mode (spi_t spi, modes_t mode)
This function configures the NRF24L01+ in TX or RX Mode.
void nrf_irqhandler (void)
Callback Function for NRF24L01+ Interrupt.
void nrf_packet_send (spi_t spi)
This function sends the packet data.
void nrf_packet_rcv (spi_t spi)
This function receives the packet data.
void nrf_write_TXaddr (spi_t spi, TX addr)
This function assigns the specified TX pipe address.
void nrf_read_TXaddr (spi_t spi)
This function reads the specified TX Pipe address.
void nrf_write_RXaddr (spi_t spi, uint8_t reg, RX addr)
This function assigns the specified RX pipe address.
void nrf_read_RXaddr (spi_t spi, uint8_t reg)
This function reads the specified RX pipe address.
void ce_status (uint8_t status)
This function changes the status of chip enable(CE) GPIO pin.
void csn_status (uint8_t status)
This function changes the status of Chip Select(CS) GPIO pin.
uint8_t nrf_get_statusreg (spi_t spi)
Thuis function returns the status register contents.
uint8_t nrf_write_cmd (spi_t spi, uint8_t cmd)
This function writes a command to the NRF24L01+.
Detailed Description
Header file for nrf_driver.c.
The file consists of all the function declarations, macros and datatype declarations required for NRF24L01+. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/16/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
FLUSH_RX_CMD
#define FLUSH_RX_CMD (0xE2)
Flush RX FIFO Command, used in Rx Mode
Definition at line 110 of file nrf_driver.h.
Referenced by nrf_config_mode().
FLUSH_TX_CMD
#define FLUSH_TX_CMD (0xE1)
Flush TX FIFO Command, used in Tx Mode
Definition at line 109 of file nrf_driver.h.
Referenced by nrf_config_mode().
HIGH
#define HIGH (1)
Definition at line 27 of file nrf_driver.h.
Referenced by nrf_config_mode(), nrf_packet_rcv(), nrf_packet_send(), nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), nrf_write_reg(), nrf_write_RXaddr(), and nrf_write_TXaddr().
LOW
#define LOW (0)
Definition at line 26 of file nrf_driver.h.
Referenced by nrf_packet_rcv(), nrf_packet_send(), nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), nrf_write_reg(), nrf_write_RXaddr(), and nrf_write_TXaddr().
MASK_RX_DR
#define MASK_RX_DR (0b01000000)
Mask Interrupt caused by RX_DR
Definition at line 93 of file nrf_driver.h.
NOP_CMD
#define NOP_CMD (0xFF)
No Operation Command which can be used to get status Register
Definition at line 108 of file nrf_driver.h.
NRF_CHIP_ENABLE_PIN
#define NRF_CHIP_ENABLE_PIN (GPIO_PIN_7)
Definition at line 34 of file nrf_driver.h.
Referenced by ce_status(), and nrf_gpio_init().
NRF_CHIP_ENABLE_PORT
#define NRF_CHIP_ENABLE_PORT (GPIO_PORTC_BASE)
Definition at line 33 of file nrf_driver.h.
Referenced by ce_status(), and nrf_gpio_init().
NRF_CHIP_SELECT_PIN
#define NRF_CHIP_SELECT_PIN (GPIO_PIN_6)
Definition at line 36 of file nrf_driver.h.
Referenced by csn_status(), and nrf_gpio_init().
NRF_CHIP_SELECT_PORT
#define NRF_CHIP_SELECT_PORT (GPIO_PORTC_BASE)
Definition at line 35 of file nrf_driver.h.
Referenced by csn_status(), and nrf_gpio_init().
NRF_CLK_PIN
#define NRF_CLK_PIN (GPIO_PIN_3)
Definition at line 46 of file nrf_driver.h.
NRF_CLK_PORT
#define NRF_CLK_PORT (GPIO_PORTD_BASE)
Definition at line 45 of file nrf_driver.h.
NRF_CONFIG_REG
#define NRF_CONFIG_REG (0x00)
Configuration Register address
Definition at line 65 of file nrf_driver.h.
Referenced by nrf_config_mode().
NRF_EN_AA_REG
#define NRF_EN_AA_REG (0x01)
AA Register address
Definition at line 66 of file nrf_driver.h.
Referenced by nrf_config_mode().
NRF_ENABLE_RXPIPE_ADDRESS_REG
#define NRF_ENABLE_RXPIPE_ADDRESS_REG (0x02)
Receiver Pipe Enable Register address
Definition at line 67 of file nrf_driver.h.
Referenced by nrf_config().
NRF_FIFO_STATUS_REG
#define NRF_FIFO_STATUS_REG (0x17)
FIFO Status Register Address
Definition at line 86 of file nrf_driver.h.
NRF_FSS_PIN
#define NRF_FSS_PIN (GPIO_PIN_2)
This pin is used for slave functionality of TIVA
Definition at line 48 of file nrf_driver.h.
NRF_FSS_PORT
#define NRF_FSS_PORT (GPIO_PORTD_BASE)
This port is used for slave functionality of TIVA
Definition at line 47 of file nrf_driver.h.
NRF_IRQ_PIN
#define NRF_IRQ_PIN (GPIO_PIN_2)
Definition at line 38 of file nrf_driver.h.
Referenced by nrf_interrupt_enable().
NRF_IRQ_PORT
#define NRF_IRQ_PORT (GPIO_PORTL_BASE)
Definition at line 37 of file nrf_driver.h.
Referenced by nrf_interrupt_enable(), and nrf_irqhandler().
NRF_MAX_RT_MASK
#define NRF_MAX_RT_MASK (0x10)
Mask for Maximum Retries
Definition at line 99 of file nrf_driver.h.
Referenced by nrf_irqhandler().
NRF_MISO_PIN
#define NRF_MISO_PIN (GPIO_PIN_1)
Definition at line 52 of file nrf_driver.h.
NRF_MISO_PORT
#define NRF_MISO_PORT (GPIO_PORTD_BASE)
Definition at line 51 of file nrf_driver.h.
NRF_MOSI_PIN
#define NRF_MOSI_PIN (GPIO_PIN_0)
Definition at line 50 of file nrf_driver.h.
NRF_MOSI_PORT
#define NRF_MOSI_PORT (GPIO_PORTD_BASE)
Definition at line 49 of file nrf_driver.h.
NRF_PORT
#define NRF_PORT (GPIO_PORTD_BASE)
Definition at line 44 of file nrf_driver.h.
NRF_RFSETUP_REG
#define NRF_RFSETUP_REG (0x06)
RF Setup Register address
Definition at line 71 of file nrf_driver.h.
NRF_RX_ADDR_P0_REG
#define NRF_RX_ADDR_P0_REG (0x0A)
Register address containing Receiver Pipe0 Address
Definition at line 73 of file nrf_driver.h.
Referenced by nrf_config().
NRF_RX_ADDR_P1_REG
#define NRF_RX_ADDR_P1_REG (0x0B)
Register address containing Receiver Pipe1 Address
Definition at line 74 of file nrf_driver.h.
NRF_RX_ADDR_P2_REG
#define NRF_RX_ADDR_P2_REG (0x0C)
Register address containing Receiver Pipe2 Address
Definition at line 75 of file nrf_driver.h.
NRF_RX_ADDR_P3_REG
#define NRF_RX_ADDR_P3_REG (0x0D)
Register address containing Receiver Pipe3 Address
Definition at line 76 of file nrf_driver.h.
NRF_RX_ADDR_P4_REG
#define NRF_RX_ADDR_P4_REG (0x0E)
Register address containing Receiver Pipe4 Address
Definition at line 77 of file nrf_driver.h.
NRF_RX_ADDR_P5_REG
#define NRF_RX_ADDR_P5_REG (0x0F)
Register address containing Receiver Pipe5 Address
Definition at line 78 of file nrf_driver.h.
NRF_RX_BYTES_P0_REG
#define NRF_RX_BYTES_P0_REG (0x11)
Register address containing Number of Data Bytes in Receiver Pipe0
Definition at line 80 of file nrf_driver.h.
Referenced by nrf_config().
NRF_RX_BYTES_P1_REG
#define NRF_RX_BYTES_P1_REG (0x12)
Register address containing Number of Data Bytes in Receiver Pipe1
Definition at line 81 of file nrf_driver.h.
NRF_RX_BYTES_P2_REG
#define NRF_RX_BYTES_P2_REG (0x13)
Register address containing Number of Data Bytes in Receiver Pipe2
Definition at line 82 of file nrf_driver.h.
NRF_RX_BYTES_P3_REG
#define NRF_RX_BYTES_P3_REG (0x14)
Register address containing Number of Data Bytes in Receiver Pipe3
Definition at line 83 of file nrf_driver.h.
NRF_RX_BYTES_P4_REG
#define NRF_RX_BYTES_P4_REG (0x15)
Register address containing Number of Data Bytes in Receiver Pipe4
Definition at line 84 of file nrf_driver.h.
NRF_RX_BYTES_P5_REG
#define NRF_RX_BYTES_P5_REG (0x16)
Register address containing Number of Data Bytes in Receiver Pipe5
Definition at line 85 of file nrf_driver.h.
NRF_RX_DR_MASK
#define NRF_RX_DR_MASK (0x40)
Mask for RX data receive
Definition at line 97 of file nrf_driver.h.
Referenced by nrf_irqhandler().
NRF_SEND
#define NRF_SEND
Definition at line 24 of file nrf_driver.h.
NRF_SETUP_AW_REG
#define NRF_SETUP_AW_REG (0x03)
Address Width Register address
Definition at line 68 of file nrf_driver.h.
NRF_SETUP_RETR_REG
#define NRF_SETUP_RETR_REG (0x04)
Retransmission Register address
Definition at line 69 of file nrf_driver.h.
NRF_SETUP_RFCHANNEL_REG
#define NRF_SETUP_RFCHANNEL_REG (0x05)
RF Channel Setup Register address
Definition at line 70 of file nrf_driver.h.
NRF_STATUS_REG
#define NRF_STATUS_REG (0x07)
Status Register address
Definition at line 72 of file nrf_driver.h.
Referenced by nrf_irqhandler().
NRF_TX_ADDR_REG
#define NRF_TX_ADDR_REG (0x10)
Register address containing Transmitter Pipe Address
Definition at line 79 of file nrf_driver.h.
Referenced by nrf_read_TXaddr(), and nrf_write_TXaddr().
NRF_TX_DS_MASK
#define NRF_TX_DS_MASK (0x20)
Mask for TX data send
Definition at line 98 of file nrf_driver.h.
Referenced by nrf_irqhandler().
R_REGISTER_CMD
#define R_REGISTER_CMD(y) (0x1F & y)
Register Read Command with Register address as Parameter
Definition at line 106 of file nrf_driver.h.
Referenced by nrf_config(), nrf_config_mode(), nrf_irqhandler(), nrf_read_RXaddr(), and nrf_read_TXaddr().
R_RX_PAYLOD_CMD
#define R_RX_PAYLOD_CMD (0x61)
Read RX Payload, Payload deleted after reading, used in RX Mode
Definition at line 111 of file nrf_driver.h.
Referenced by nrf_irqhandler(), and nrf_packet_rcv().
READ_MASK
#define READ_MASK (0xFF)
Definition at line 58 of file nrf_driver.h.
RF_DR_LOW
#define RF_DR_LOW (0b00100000)
Definition at line 95 of file nrf_driver.h.
RF_DR_LOW250
#define RF_DR_LOW250 (5)
Bit to set data rate to 250kbps
Definition at line 92 of file nrf_driver.h.
SHIFT
#define SHIFT(y) (1<<y)
Definition at line 28 of file nrf_driver.h.
W_REGISTER_CMD
#define W_REGISTER_CMD(y) (0x20 | y)
Register Write Command with Register address as Parameter
Definition at line 107 of file nrf_driver.h.
Referenced by nrf_config(), nrf_config_mode(), nrf_irqhandler(), nrf_write_RXaddr(), and nrf_write_TXaddr().
W_TX_PAYLOD_CMD
#define W_TX_PAYLOD_CMD (0xA0)
Read RX Payload, used in TX Mode
Definition at line 112 of file nrf_driver.h.
Referenced by nrf_packet_send().
WRITE
#define WRITE MASK (0x20)
Definition at line 59 of file nrf_driver.h.
Enumeration Type Documentation
modes_t
enum modes_t
Enumerator
mode_tx
mode_rx
Definition at line 130 of file nrf_driver.h.
Function Documentation
ce_status()
void ce_status (uint8_t status) [inline]
This function changes the status of chip enable(CE) GPIO pin.
Parameters
status This value is a macro HIGH or LOW which specifies the pin to go high or low.
Returns
void
Definition at line 254 of file nrf_driver.h.
References NRF_CHIP_ENABLE_PIN, and NRF_CHIP_ENABLE_PORT.
Referenced by nrf_config_mode().
csn_status()
void csn_status (uint8_t status) [inline]
This function changes the status of Chip Select(CS) GPIO pin.
Parameters
status This value is a macro HIGH or LOW which specifies the pin to go high or low.
Returns
void.
Definition at line 271 of file nrf_driver.h.
References NRF_CHIP_SELECT_PIN, and NRF_CHIP_SELECT_PORT.
Referenced by nrf_packet_rcv(), nrf_packet_send(), nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), nrf_write_reg(), nrf_write_RXaddr(), and nrf_write_TXaddr().
nrf_config()
void nrf_config (void)
This function configures the register value for NRF24L01+.
Returns
void.
Definition at line 88 of file nrf_driver.c.
References mode_tx, nrf_config_mode(), NRF_ENABLE_RXPIPE_ADDRESS_REG, nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), NRF_RX_ADDR_P0_REG, NRF_RX_BYTES_P0_REG, nrf_write_reg(), nrf_write_RXaddr(), nrf_write_TXaddr(), printf, R_REGISTER_CMD, RX::rx_pipe_address, SPI2, TX::tx_pipe_address, and W_REGISTER_CMD.
nrf_config_mode()
void nrf_config_mode (spi_t spi, modes_t mode)
This function configures the NRF24L01+ in TX or RX Mode.
Parameters
spi The SPI line used.
mode The mode specified by the user.
Definition at line 190 of file nrf_driver.c.
References ce_status(), FLUSH_RX_CMD, FLUSH_TX_CMD, HIGH, mode_rx, mode_tx, NRF_CONFIG_REG, NRF_EN_AA_REG, nrf_packet_send(), nrf_read_reg(), nrf_write_cmd(), nrf_write_reg(), printf, R_REGISTER_CMD, SPI2, and W_REGISTER_CMD.
Referenced by nrf_config().
nrf_get_statusreg()
uint8_t nrf_get_statusreg (spi_t spi) [inline]
Thuis function returns the status register contents.
Parameters
spi The SPI line used.
Returns
uint8_t The contents of Status register.
Definition at line 289 of file nrf_driver.h.
References spi_dummy_transfer().
nrf_gpio_init()
void nrf_gpio_init (void)
This function initializes all the GPIOs required by the NRF25L01+.
The Pins are: Chip Enable, Chip Select and IRQ pin.
Returns
void
Definition at line 18 of file nrf_driver.c.
References NRF_CHIP_ENABLE_PIN, NRF_CHIP_ENABLE_PORT, NRF_CHIP_SELECT_PIN, NRF_CHIP_SELECT_PORT, and nrf_interrupt_enable().
nrf_interrupt_enable()
void nrf_interrupt_enable (void)
This function configures and enables the GPIO interrupt for NRF24L01+.
Returns
void.
Definition at line 37 of file nrf_driver.c.
References NRF_IRQ_PIN, NRF_IRQ_PORT, and nrf_irqhandler().
Referenced by nrf_gpio_init().
nrf_irqhandler()
void nrf_irqhandler (void)
Callback Function for NRF24L01+ Interrupt.
This function is called whenever there is an interrupt on the IRQ pin of NRF24L01+. The interrupt is due to data received and transmitted.
Returns
void.
Definition at line 369 of file nrf_driver.c.
References NRF_IRQ_PORT, NRF_MAX_RT_MASK, nrf_packet_rcv(), nrf_read_reg(), NRF_RX_DR_MASK, NRF_STATUS_REG, NRF_TX_DS_MASK, nrf_write_reg(), printf, R_REGISTER_CMD, R_RX_PAYLOD_CMD, SPI2, spi_dummy_transfer(), spi_transfer(), and W_REGISTER_CMD.
Referenced by nrf_interrupt_enable().
nrf_packet_rcv()
void nrf_packet_rcv (spi_t spi)
This function receives the packet data.
Parameters
spi The SPI line used.
Definition at line 281 of file nrf_driver.c.
References csn_status(), HIGH, LOW, printf, R_RX_PAYLOD_CMD, SPI2, and spi_transfer().
Referenced by nrf_irqhandler().
nrf_packet_send()
void nrf_packet_send (spi_t spi)
This function sends the packet data.
Parameters
spi The SPI line used.
Definition at line 248 of file nrf_driver.c.
References csn_status(), HIGH, LOW, spi_transfer(), and W_TX_PAYLOD_CMD.
Referenced by nrf_config_mode().
nrf_read_reg()
uint8_t nrf_read_reg (spi_t spi, uint8_t reg)
This function reads the value from the register specified by the parameter reg.
Parameters
spi The SPI line used.
reg The Register value to read data from.
Returns
uint8_t The value read from the register reg.
Definition at line 73 of file nrf_driver.c.
References csn_status(), HIGH, LOW, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config(), nrf_config_mode(), and nrf_irqhandler().
nrf_read_RXaddr()
void nrf_read_RXaddr (spi_t spi, uint8_t reg)
This function reads the specified RX pipe address.
Parameters
spi The SPI line used.
reg The Register address of the PIPE.
Definition at line 350 of file nrf_driver.c.
References csn_status(), HIGH, LOW, printf, R_REGISTER_CMD, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config().
nrf_read_TXaddr()
void nrf_read_TXaddr (spi_t spi)
This function reads the specified TX Pipe address.
Parameters
spi The SPI line used.
Definition at line 315 of file nrf_driver.c.
References csn_status(), HIGH, LOW, NRF_TX_ADDR_REG, printf, R_REGISTER_CMD, spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config().
nrf_write_cmd()
uint8_t nrf_write_cmd (spi_t spi, uint8_t cmd) [inline]
This function writes a command to the NRF24L01+.
Parameters
spi The SPI line used.
cmd The Command MACRO.
Definition at line 299 of file nrf_driver.h.
References spi_dummy_transfer(), and spi_transfer().
Referenced by nrf_config_mode().
nrf_write_reg()
void nrf_write_reg (spi_t spi, uint8_t reg, uint8_t value)
This function writes to a register in the NRF24L01+.
Parameters
spi The SPI line used.
reg The Register value to write to.
value The value to write to the Register.
Returns
void.
Definition at line 60 of file nrf_driver.c.
References csn_status(), HIGH, LOW, and spi_transfer().
Referenced by nrf_config(), nrf_config_mode(), and nrf_irqhandler().
nrf_write_RXaddr()
void nrf_write_RXaddr (spi_t spi, uint8_t reg, RX addr)
This function assigns the specified RX pipe address.
Parameters
spi The SPI line used.
reg The Register address of the PIPE.
addr The object of structure RX.
Definition at line 333 of file nrf_driver.c.
References csn_status(), HIGH, LOW, RX::rx_pipe_address, spi_transfer(), and W_REGISTER_CMD.
Referenced by nrf_config().
nrf_write_TXaddr()
void nrf_write_TXaddr (spi_t spi, TX addr)
This function assigns the specified TX pipe address.
Parameters
spi The SPI line used
addr The object of structure TX.
Definition at line 299 of file nrf_driver.c.
References csn_status(), HIGH, LOW, NRF_TX_ADDR_REG, spi_transfer(), TX::tx_pipe_address, and W_REGISTER_CMD.
Referenced by nrf_config().