inc/packet.h File Reference
Header file for packet.c.
#include `inc/main.h`
#include `inc/myuart.h`
Macros
#define PREAMBLE (0xAB)
#define POSTAMBLE (0xBA)
Functions
struct __attribute__ ((__packed__))
packet packet_make (uint8_t event_id, uint8_t *payload, uint16_t size, uint8_t ack)
This function populates the structure with payload to send to beaglebone.
void packet_send_uart (uart_t uart, packet data_send)
This function sends the packet over the specified UART line and starts timer for packet acknowledgment retries.
packet packet_rcv_uart (uart_t uart)
This function receives the packet and populates the received data in a Packet structure and sends acknowledgement if ack bit is set.
void packet_msglog_uart (uart_t uart, uint8_t *msg_log)
This function sends a message to be logged to the Beaglebone (Control Node).
void packet_loopback_test (void)
This function is used to test send and receive data.
Variables
packet
Detailed Description
Header file for packet.c.
The file consists of all the function declarations, macros and typedefs related to Creating packet structure. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo.
Date
04/26/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
POSTAMBLE
#define POSTAMBLE (0xBA)
Definition at line 27 of file packet.h.
Referenced by packet_make().
PREAMBLE
#define PREAMBLE (0xAB)
Definition at line 26 of file packet.h.
Referenced by packet_make(), and uart_packet_handler().
Function Documentation
__attribute__()
struct __attribute__ ((__packed__))
Definition at line 31 of file packet.h.
packet_loopback_test()
void packet_loopback_test (void)
This function is used to test send and receive data.
Returns
void.
Definition at line 126 of file packet.c.
References configureUART_bbg(), delay_ms(), packet, packet_make(), packet_rcv_uart(), packet_send_uart(), and UART_BBG.
packet_make()
packet packet_make (uint8_t event_id, uint8_t * payload, uint16_t size, uint8_t ack)
This function populates the structure with payload to send to beaglebone.
Parameters
event_id This event signifies the type of data contained by the payload.
payload The data that needs to be passed via payload.
size The size of the array.
ack This bit is set if acknowledge feature is enabled.
Returns
packet The packet structure.
Definition at line 22 of file packet.c.
References checksum_calc(), packet, POSTAMBLE, PREAMBLE, and printf.
Referenced by ack_send_uart(), column_handler(), fp_access_handle(), packet_loopback_test(), and packet_msglog_uart().
packet_msglog_uart()
void packet_msglog_uart (uart_t uart, uint8_t * msg_log)
This function sends a message to be logged to the Beaglebone (Control Node).
Parameters
uart The UART line used.
msg_log The String to send to the Control Node.
Definition at line 119 of file packet.c.
References MSG_LOG_ID, packet_make(), packet_send_uart(), and TRUE.
packet_rcv_uart()
packet packet_rcv_uart (uart_t uart)
This function receives the packet and populates the received data in a Packet structure and sends acknowledgement if ack bit is set.
Parameters
uart The UARt line used.
Returns
packet The packet structure in which the data has been populated.
Definition at line 73 of file packet.c.
References ack_send_uart(), checksum_calc(), packet, printf, and UART_BBG.
Referenced by packet_loopback_test(), and uart_commhandler().
packet_send_uart()
void packet_send_uart (uart_t uart, packet data_send)
This function sends the packet over the specified UART line and starts timer for packet acknowledgment retries.
Parameters
uart The UARt line used.
data_send The packet structure object to send.
Returns
void.
Definition at line 43 of file packet.c.
References enable_timer_int(), timer_retry, and uart_send().
Referenced by ack_send_uart(), column_handler(), fp_access_handle(), packet_loopback_test(), and packet_msglog_uart().
Variable Documentation
packet
packet
Definition at line 41 of file packet.h.
Referenced by packet_loopback_test(), packet_make(), and packet_rcv_uart().