inc/spi.h File Reference
Header file for spi.c.
#include `inc/main.h`
#include `driverlib/ssi.h`
Enumerations
enum spi_t { SPI0 = SSI0_BASE,
SPI1 = SSI1_BASE,
SPI2 = SSI2_BASE
 }
Functions
void spi_config (spi_t ssi_x)
This function configures the SPI line as per the parameters.
uint8_t spi_transfer (spi_t spi, uint8_t value)
This function transfers a value on the MOSI line and reads the data on the MISO line.
uint8_t spi_dummy_transfer (spi_t spi)
This function transfers a NO OPERATION Command and reads data from the MISO line.
void spi_busy (spi_t spi)
This function checks the SPI line if it is busy or not.
Detailed Description
Header file for spi.c.
The file consists of all the function declarations, macros and datatype declarations related to SPI functionality. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/16/2019
Copyright
Copyright (c) 2019
Enumeration Type Documentation
spi_t
enum spi_t
Enumerator
SPI0
SPI1
SPI2
Definition at line 30 of file spi.h.
Function Documentation
spi_busy()
void spi_busy (spi_t spi) [inline]
This function checks the SPI line if it is busy or not.
Parameters
spi The SPI line used.
Returns
void.
Definition at line 146 of file spi.c.
Referenced by spi_transfer().
spi_config()
void spi_config (spi_t ssi_x)
This function configures the SPI line as per the parameters.
Parameters
ssi_x The SPI line used.
Returns
void
Definition at line 24 of file spi.c.
References g_ui32SysClock, SPI0, SPI1, and SPI2.
spi_dummy_transfer()
uint8_t spi_dummy_transfer (spi_t spi)
This function transfers a NO OPERATION Command and reads data from the MISO line.
Parameters
spi The SPI line used.
Returns
uint8_t The value read from the MISO line on the specified SPI.
Definition at line 140 of file spi.c.
References spi_transfer().
Referenced by nrf_get_statusreg(), nrf_irqhandler(), nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), and nrf_write_cmd().
spi_transfer()
uint8_t spi_transfer (spi_t spi, uint8_t value)
This function transfers a value on the MOSI line and reads the data on the MISO line.
Parameters
spi The SPI line used.
value The value transfered on the SPI line. This can be a register address or the value to be written to the register value.
Returns
uint8_t The value read from the MISO line on the specified SPI.
Definition at line 130 of file spi.c.
References SPI2, and spi_busy().
Referenced by nrf_irqhandler(), nrf_packet_rcv(), nrf_packet_send(), nrf_read_reg(), nrf_read_RXaddr(), nrf_read_TXaddr(), nrf_write_cmd(), nrf_write_reg(), nrf_write_RXaddr(), nrf_write_TXaddr(), and spi_dummy_transfer().