src/temp.c File Reference
#include <string.h>
#include `inc/temp.h`
#include `inc/msg_queue.h`
#include `inc/sync_objects.h`
Functions
uint8_t temptask_init (void)
This function creates Temperature Task.
void temp_write (void)
8 bit write function
float temp_read (void)
This function reads 2 byte Temperature register using I2C.
void temp_send (void)
The function receives data from the temperature sensor and sends it to the logger task via message queue.
static void temp (void *pvParameters)
Callback function for Temperature Task.
Function Documentation
temp()
static void temp (void * pvParameters) [static]
Callback function for Temperature Task.
Returns
void
Definition at line 110 of file temp.c.
References g_qsem, g_temp, g_uartsem, nrf_log_mq, and RANDOM_TEST_ID.
Referenced by fp_responsercv(), and temp_read().
temp_read()
float temp_read (void)
This function reads 2 byte Temperature register using I2C.
Returns
void
Definition at line 53 of file temp.c.
References SLAVE_ADDR, temp(), and temp_write().
Referenced by temp_send().
temp_send()
void temp_send (void)
The function receives data from the temperature sensor and sends it to the logger task via message queue.
Returns
void
Definition at line 87 of file temp.c.
References g_qsem, g_uartsem, nrf_log_mq, TEMP_RCV_ID, and temp_read().
temp_write()
void temp_write (void)
8 bit write function
Returns
void
Definition at line 36 of file temp.c.
References CONFIG_TEMP, and SLAVE_ADDR.
Referenced by temp_read().
temptask_init()
uint8_t temptask_init (void)
This function creates Temperature Task.
Returns
uint8_t
Definition at line 19 of file temp.c.
References LEDTASKSTACKSIZE.