inc/temp.h File Reference
Header file for temp.c.
#include `inc/main.h`
Macros
#define CONFIG_TEMP (0x00)
#define SLAVE_ADDR (0x48)
#define THRESHOLD (25)
Functions
uint8_t temptask_init (void)
This function creates Temperature Task.
static void temp (void *pvParameters)
void temp_send (void)
The function receives data from the temperature sensor and sends it to the logger task via message queue.
float temp_read (void)
This function reads 2 byte Temperature register using I2C.
Detailed Description
Header file for temp.c.
The file consists of all the function declarations, macros and typedefs related to Temperature functionality. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Satya Mehta
Date
04/14/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
CONFIG_TEMP
#define CONFIG_TEMP (0x00)
Definition at line 20 of file temp.h.
Referenced by temp_write().
SLAVE_ADDR
#define SLAVE_ADDR (0x48)
Definition at line 21 of file temp.h.
Referenced by temp_read(), and temp_write().
THRESHOLD
#define THRESHOLD (25)
Definition at line 22 of file temp.h.
Function Documentation
temp()
static void temp (void * pvParameters) [static]
temp_read()
float temp_read (void)
This function reads 2 byte Temperature register using I2C.
Returns
void
Definition at line 53 of file temp.c.
References SLAVE_ADDR, temp(), and temp_write().
Referenced by temp_send().
temp_send()
void temp_send (void)
The function receives data from the temperature sensor and sends it to the logger task via message queue.
Returns
void
Definition at line 87 of file temp.c.
References g_qsem, g_uartsem, nrf_log_mq, TEMP_RCV_ID, and temp_read().
temptask_init()
uint8_t temptask_init (void)
This function creates Temperature Task.
Returns
uint8_t
Definition at line 19 of file temp.c.
References LEDTASKSTACKSIZE.