inc/timer.h File Reference
Header file for timer.c.
#include `inc/main.h`
Macros
#define OTP_INPUT_TIME (120000)
#define PACKET_RETRY_TIME (500)
#define PACKET_RETRY_COUNT (3)
Enumerations
enum timer_t { timer_retry = TIMER0_BASE,
timer_otp = TIMER1_BASE
 }
Functions
void timer_config (timer_t timer, uint32_t ms)
This function creates, initializes and enables TIMER0A and TIMER1A.
void enable_timer_int (timer_t timer)
This function enbale the Timer Interrupts.
void disable_timer (timer_t timer)
This function disables the timer and resets it.
void reset_timer (timer_t timer, uint32_t ms)
This function resets the timer to the specified time.
void timer0handler (void)
Callback Function for Temperature Timer(TIMER0A).
void timer1handler (void)
Callback Function for LED Timer(TIMER0A).
Variables
static uint8_t send_failcount
Detailed Description
Header file for timer.c.
The file consists of all the function declarations, macros and typedefs related to TIMER functionality. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/12/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
OTP_INPUT_TIME
#define OTP_INPUT_TIME (120000)
Time to input OTP is in Milliseconds (120 seconds)
Definition at line 32 of file timer.h.
Referenced by timer1handler(), and uart_packet_handler().
PACKET_RETRY_COUNT
#define PACKET_RETRY_COUNT (3)
Max Packet Retry Counts
Definition at line 34 of file timer.h.
Referenced by timer0handler().
PACKET_RETRY_TIME
#define PACKET_RETRY_TIME (500)
Retry time in Milliseconds
Definition at line 33 of file timer.h.
Referenced by timer0handler(), and uart_packet_handler().
Enumeration Type Documentation
timer_t
enum timer_t
Enumerator
timer_retry
timer_otp
Definition at line 22 of file timer.h.
Function Documentation
disable_timer()
void disable_timer (timer_t timer) [inline]
This function disables the timer and resets it.
Parameters
timer The enum of type timer_t.
Returns
void
Definition at line 67 of file timer.c.
Referenced by timer0handler(), timer1handler(), and uart_packet_handler().
enable_timer_int()
void enable_timer_int (timer_t timer)
This function enbale the Timer Interrupts.
Parameters
timer The enum of type timer_t.
Returns
void.
Definition at line 58 of file timer.c.
Referenced by packet_send_uart(), and uart_packet_handler().
reset_timer()
void reset_timer (timer_t timer, uint32_t ms) [inline]
This function resets the timer to the specified time.
Parameters
timer The enum of type timer_t.
ms Timer Period in milliseconds.
Returns
void.
Definition at line 74 of file timer.c.
References g_ui32SysClock.
Referenced by timer0handler(), timer1handler(), and uart_packet_handler().
timer0handler()
void timer0handler (void)
Callback Function for Temperature Timer(TIMER0A).
Returns
void.
Definition at line 80 of file timer.c.
References disable_timer(), PACKET_RETRY_COUNT, PACKET_RETRY_TIME, printf, reset_timer(), send_failcount, and timer_retry.
timer1handler()
void timer1handler (void)
Callback Function for LED Timer(TIMER0A).
Returns
void.
Definition at line 110 of file timer.c.
References delay_ms(), disable_timer(), fp_interrupt_enable(), LCD_write(), otp_arr, otp_count, otp_flag, OTP_INPUT_TIME, printf, reset_timer(), and timer_otp.
timer_config()
void timer_config (timer_t timer, uint32_t ms)
This function creates, initializes and enables TIMER0A and TIMER1A.
Parameters
timer The enum of type timer_t.
ms Timer Period in milliseconds.
Returns
void
Definition at line 22 of file timer.c.
References g_ui32SysClock, timer_otp, and timer_retry.
Variable Documentation
send_failcount
uint8_t send_failcount [static]
Definition at line 29 of file timer.h.
Referenced by timer0handler(), and uart_packet_handler().