src/timer.c File Reference
This file consists of all the functions required for Timer initialization, enable and callback functions.
#include `inc/timer.h`
#include `inc/sync_objects.h`
#include `inc/keypad.h`
#include `inc/delay.h`
#include `inc/fingerprint.h`
#include `inc/lcd.h`
Functions
void timer_config (timer_t timer, uint32_t ms)
This function creates, initializes and enables TIMER0A and TIMER1A.
void enable_timer_int (timer_t timer)
This function enbale the Timer Interrupts.
void disable_timer (timer_t timer)
This function disables the timer and resets it.
void reset_timer (timer_t timer, uint32_t ms)
This function resets the timer to the specified time.
void timer0handler (void)
Callback Function for Temperature Timer(TIMER0A).
void timer1handler (void)
Callback Function for LED Timer(TIMER0A).
Detailed Description
This file consists of all the functions required for Timer initialization, enable and callback functions.
The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/13/2019
Copyright
Copyright (c) 2019
Function Documentation
disable_timer()
void disable_timer (timer_t timer) [inline]
This function disables the timer and resets it.
Parameters
timer The enum of type timer_t.
Returns
void
Definition at line 67 of file timer.c.
Referenced by timer0handler(), timer1handler(), and uart_packet_handler().
enable_timer_int()
void enable_timer_int (timer_t timer)
This function enbale the Timer Interrupts.
Parameters
timer The enum of type timer_t.
Returns
void.
Definition at line 58 of file timer.c.
Referenced by packet_send_uart(), and uart_packet_handler().
reset_timer()
void reset_timer (timer_t timer, uint32_t ms) [inline]
This function resets the timer to the specified time.
Parameters
timer The enum of type timer_t.
ms Timer Period in milliseconds.
Returns
void.
Definition at line 74 of file timer.c.
References g_ui32SysClock.
Referenced by timer0handler(), timer1handler(), and uart_packet_handler().
timer0handler()
void timer0handler (void)
Callback Function for Temperature Timer(TIMER0A).
Returns
void.
Definition at line 80 of file timer.c.
References disable_timer(), PACKET_RETRY_COUNT, PACKET_RETRY_TIME, printf, reset_timer(), send_failcount, and timer_retry.
timer1handler()
void timer1handler (void)
Callback Function for LED Timer(TIMER0A).
Returns
void.
Definition at line 110 of file timer.c.
References delay_ms(), disable_timer(), fp_interrupt_enable(), LCD_write(), otp_arr, otp_count, otp_flag, OTP_INPUT_TIME, printf, reset_timer(), and timer_otp.
timer_config()
void timer_config (timer_t timer, uint32_t ms)
This function creates, initializes and enables TIMER0A and TIMER1A.
Parameters
timer The enum of type timer_t.
ms Timer Period in milliseconds.
Returns
void
Definition at line 22 of file timer.c.
References g_ui32SysClock, timer_otp, and timer_retry.