inc/uart_comm_bbg.h File Reference
Header file for uart_comm_bbg.c.
#include `inc/main.h`
#include `inc/myuart.h`
#include `inc/packet.h`
Macros
#define BAUDRATE_BBG (115200)
Functions
void configureUART_bbg (void)
This function configures the UART to communicate with beaglebone.
void uart_packet_handler (packet datap_rcv)
This function handles the received packet.
void uart_commhandler (void)
Interrupt Handler for UART Communication with BBG.
void uart_bbg_test (void)
This function is used for testing UART communication with beaglebone.
void ack_send_uart (uart_t uart)
This function sends an acknowledgment for the receoved packet.
Detailed Description
Header file for uart_comm_bbg.c.
The file consists of all the function declarations, macros and datatype declarations for UART Communication. The Code has been executed on TIVA C Series TM4C1294XL on FreeRTOS.
Author
Siddhant Jajoo
Date
04/20/2019
Copyright
Copyright (c) 2019
Macro Definition Documentation
BAUDRATE_BBG
#define BAUDRATE_BBG (115200)
Definition at line 23 of file uart_comm_bbg.h.
Referenced by configureUART_bbg().
Function Documentation
ack_send_uart()
void ack_send_uart (uart_t uart) [inline]
This function sends an acknowledgment for the receoved packet.
Parameters
uart The UART line used.
Returns
void.
Definition at line 66 of file uart_comm_bbg.h.
References ACK_ID, DONT_CARE, FALSE, packet_make(), packet_send_uart(), and UART_BBG.
Referenced by packet_rcv_uart().
configureUART_bbg()
void configureUART_bbg (void)
This function configures the UART to communicate with beaglebone.
Returns
void.
Definition at line 26 of file uart_comm_bbg.c.
References BAUDRATE_BBG, CLOCK, UART_BBG, uart_comm_flushRX(), uart_comm_flushTX(), and uart_commhandler().
Referenced by packet_loopback_test(), and uart_bbg_test().
uart_bbg_test()
void uart_bbg_test (void)
This function is used for testing UART communication with beaglebone.
Returns
void.
Definition at line 197 of file uart_comm_bbg.c.
References configureUART_bbg(), printf, UART_BBG, and uart_send().
uart_commhandler()
void uart_commhandler (void)
Interrupt Handler for UART Communication with BBG.
Returns
void.
Definition at line 162 of file uart_comm_bbg.c.
References packet_rcv_uart(), printf, UART_BBG, and uart_packet_handler().
Referenced by configureUART_bbg().
uart_packet_handler()
void uart_packet_handler (packet datap_rcv)
This function handles the received packet.
Parameters
datap_rcv The packet structure object.
Returns
void.
Definition at line 67 of file uart_comm_bbg.c.
References ACCESS_STATUS_RCV_ID, ACK_ID, add_fingerprint(), buzzer_onoff(), checksum_calc(), disable_timer(), enable_timer_int(), fp_deleteall(), fp_interrupt_disable(), fp_interrupt_enable(), GUI_ADD_FINGERPRINT, GUI_BUZZER_OFF, GUI_BUZZER_ON, GUI_DELETE_FINGERPRINT_ALL, GUI_ID, GUI_RESET_SYSTEM, keypad_interrupt_enable(), LCD_write(), otp_arr, otp_count, otp_flag, OTP_INPUT_TIME, OTP_SENT_USER_ID, PACKET_RETRY_TIME, PREAMBLE, printf, reset_timer(), send_failcount, timer_otp, timer_retry, and UART_FP.
Referenced by uart_commhandler().